//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iDAS.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccountingPayment
    {
        public AccountingPayment()
        {
            this.AccountingPaymentPlans = new HashSet<AccountingPaymentPlan>();
        }
    
        public int ID { get; set; }
        public int CustomerContractID { get; set; }
        public string Content { get; set; }
        public Nullable<decimal> Rate { get; set; }
        public Nullable<decimal> Value { get; set; }
        public bool IsCustomer { get; set; }
        public bool IsDelete { get; set; }
        public string Note { get; set; }
        public Nullable<int> CreateBy { get; set; }
        public Nullable<System.DateTime> CreateAt { get; set; }
        public Nullable<int> UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdateAt { get; set; }
    
        public virtual ICollection<AccountingPaymentPlan> AccountingPaymentPlans { get; set; }
        public virtual CustomerContract CustomerContract { get; set; }
    }
}
