//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iDAS.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccountingSpendingBill
    {
        public int ID { get; set; }
        public string Code { get; set; }
        public Nullable<System.DateTime> RefDate { get; set; }
        public Nullable<int> AccountingSuggestAdvanceID { get; set; }
        public Nullable<int> HumanEmployeeID { get; set; }
        public int AccountingReasonSpendingID { get; set; }
        public string Receiver { get; set; }
        public string Address { get; set; }
        public Nullable<System.DateTime> CreateAt { get; set; }
        public Nullable<int> CreateBy { get; set; }
        public Nullable<System.DateTime> UpdateAt { get; set; }
        public Nullable<int> UpdateBy { get; set; }
    }
}
