//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iDAS.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccountingSpendingBillDetail
    {
        public int ID { get; set; }
        public int AccountingSpendingBillID { get; set; }
        public decimal CreditAccount { get; set; }
        public decimal DebitAccount { get; set; }
        public decimal Account { get; set; }
        public Nullable<int> HumanEmployeeID { get; set; }
        public Nullable<System.DateTime> CreateAt { get; set; }
        public Nullable<int> CreateBy { get; set; }
        public Nullable<System.DateTime> UpdateAt { get; set; }
        public Nullable<int> UpdateBy { get; set; }
    }
}
