//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iDAS.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class Audit
    {
        public Audit()
        {
            this.AuditResults = new HashSet<AuditResult>();
            this.CustomerAssesses = new HashSet<CustomerAssess>();
            this.CustomerCampaignAudits = new HashSet<CustomerCampaignAudit>();
            this.Tasks = new HashSet<Task>();
        }
    
        public int ID { get; set; }
        public int QualityCriteriaCategoryID { get; set; }
        public int EmployeeID { get; set; }
        public bool IsPass { get; set; }
        public System.DateTime Time { get; set; }
        public string Note { get; set; }
        public Nullable<System.DateTime> CreateAt { get; set; }
        public Nullable<int> CreateBy { get; set; }
        public Nullable<System.DateTime> UpdateAt { get; set; }
        public Nullable<int> UpdateBy { get; set; }
    
        public virtual ICollection<AuditResult> AuditResults { get; set; }
        public virtual QualityCriteriaCategory QualityCriteriaCategory { get; set; }
        public virtual ICollection<CustomerAssess> CustomerAssesses { get; set; }
        public virtual ICollection<CustomerCampaignAudit> CustomerCampaignAudits { get; set; }
        public virtual ICollection<Task> Tasks { get; set; }
    }
}
