//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iDAS.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class CalendarOverride
    {
        public CalendarOverride()
        {
            this.CalendarTimeOverrides = new HashSet<CalendarTimeOverride>();
        }
    
        public int ID { get; set; }
        public Nullable<int> TaskCalendarEventID { get; set; }
        public int CalendarCategoryID { get; set; }
        public string Title { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public bool IsDayOverrides { get; set; }
        public Nullable<System.DateTime> CreateAt { get; set; }
        public Nullable<int> CreateBy { get; set; }
        public Nullable<System.DateTime> UpdateAt { get; set; }
        public Nullable<int> UpdateBy { get; set; }
    
        public virtual CalendarCategory CalendarCategory { get; set; }
        public virtual TaskCalendarEvent TaskCalendarEvent { get; set; }
        public virtual ICollection<CalendarTimeOverride> CalendarTimeOverrides { get; set; }
    }
}
