//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iDAS.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class CenterSystem
    {
        public CenterSystem()
        {
            this.CustomerSystems = new HashSet<CustomerSystem>();
        }
    
        public int ID { get; set; }
        public string SystemCode { get; set; }
        public string Name { get; set; }
        public string Url { get; set; }
        public string DBSource { get; set; }
        public string DBUserID { get; set; }
        public string DBPassword { get; set; }
        public string MailHost { get; set; }
        public Nullable<int> MailPort { get; set; }
        public Nullable<bool> MailEnableSsl { get; set; }
        public string MailUserName { get; set; }
        public string MailUserPassword { get; set; }
        public byte[] ImageUser { get; set; }
        public byte[] ImageLogo { get; set; }
        public string Description { get; set; }
        public bool IsActive { get; set; }
        public bool IsDelete { get; set; }
        public Nullable<System.DateTime> CreateAt { get; set; }
        public Nullable<int> CreateBy { get; set; }
        public Nullable<System.DateTime> UpdateAt { get; set; }
        public Nullable<int> UpdateBy { get; set; }
        public string DocumentFolder { get; set; }
    
        public virtual ICollection<CustomerSystem> CustomerSystems { get; set; }
    }
}
