//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iDAS.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerCriteria
    {
        public CustomerCriteria()
        {
            this.CustomerAssessResults = new HashSet<CustomerAssessResult>();
        }
    
        public int ID { get; set; }
        public int CustomerCriteriaCategoryID { get; set; }
        public string Name { get; set; }
        public bool IsActive { get; set; }
        public bool IsDelete { get; set; }
        public int MinPoint { get; set; }
        public int MaxPoint { get; set; }
        public decimal Factory { get; set; }
        public Nullable<System.DateTime> CreateAt { get; set; }
        public Nullable<int> CreateBy { get; set; }
        public Nullable<System.DateTime> UpdateAt { get; set; }
        public Nullable<int> UpdateBy { get; set; }
    
        public virtual ICollection<CustomerAssessResult> CustomerAssessResults { get; set; }
        public virtual CustomerCriteriaCategory CustomerCriteriaCategory { get; set; }
    }
}
