//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iDAS.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerCampaign
    {
        public CustomerCampaign()
        {
            this.CustomerCampaignAudits = new HashSet<CustomerCampaignAudit>();
            this.CustomerCampaignPlans = new HashSet<CustomerCampaignPlan>();
            this.CustomerCampaignTargets = new HashSet<CustomerCampaignTarget>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public System.DateTime StartTime { get; set; }
        public System.DateTime EndTime { get; set; }
        public decimal Cost { get; set; }
        public bool IsEdit { get; set; }
        public bool IsApproval { get; set; }
        public bool IsAccept { get; set; }
        public bool IsPause { get; set; }
        public bool IsFinish { get; set; }
        public bool IsSuccess { get; set; }
        public bool IsDelete { get; set; }
        public Nullable<decimal> Income { get; set; }
        public string Note { get; set; }
        public Nullable<int> ApprovalBy { get; set; }
        public Nullable<System.DateTime> ApprovalAt { get; set; }
        public string ApprovalNote { get; set; }
        public Nullable<System.DateTime> CreateAt { get; set; }
        public Nullable<int> CreateBy { get; set; }
        public Nullable<System.DateTime> UpdateAt { get; set; }
        public Nullable<int> UpdateBy { get; set; }
    
        public virtual ICollection<CustomerCampaignAudit> CustomerCampaignAudits { get; set; }
        public virtual ICollection<CustomerCampaignPlan> CustomerCampaignPlans { get; set; }
        public virtual ICollection<CustomerCampaignTarget> CustomerCampaignTargets { get; set; }
    }
}
