//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iDAS.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerContact
    {
        public int ID { get; set; }
        public int CustomerID { get; set; }
        public Nullable<System.Guid> AttachmentFileID { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public bool Sex { get; set; }
        public string Phone { get; set; }
        public Nullable<System.DateTime> Birthday { get; set; }
        public bool IsDelete { get; set; }
        public string Role { get; set; }
        public string Department { get; set; }
        public string Address { get; set; }
        public string Note { get; set; }
        public Nullable<int> CreateBy { get; set; }
        public Nullable<System.DateTime> CreateAt { get; set; }
        public Nullable<int> UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdateAt { get; set; }
    
        public virtual AttachmentFile AttachmentFile { get; set; }
        public virtual Customer Customer { get; set; }
    }
}
