//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iDAS.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerOrder
    {
        public CustomerOrder()
        {
            this.CustomerOrderAttachmentFiles = new HashSet<CustomerOrderAttachmentFile>();
        }
    
        public int ID { get; set; }
        public int CustomerID { get; set; }
        public int ServiceID { get; set; }
        public Nullable<int> CustomerContractID { get; set; }
        public int Quantity { get; set; }
        public System.DateTime Time { get; set; }
        public bool IsPrice { get; set; }
        public bool IsPause { get; set; }
        public bool IsFinish { get; set; }
        public bool IsSuccess { get; set; }
        public string Note { get; set; }
        public Nullable<System.DateTime> CreateAt { get; set; }
        public Nullable<int> CreateBy { get; set; }
        public Nullable<System.DateTime> UpdateAt { get; set; }
        public Nullable<int> UpdateBy { get; set; }
    
        public virtual CustomerContract CustomerContract { get; set; }
        public virtual ICollection<CustomerOrderAttachmentFile> CustomerOrderAttachmentFiles { get; set; }
        public virtual Customer Customer { get; set; }
        public virtual Service Service { get; set; }
    }
}
