//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iDAS.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerSurvey
    {
        public CustomerSurvey()
        {
            this.CustomerSurveyObjects = new HashSet<CustomerSurveyObject>();
            this.CustomerSurveyQuestions = new HashSet<CustomerSurveyQuestion>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public System.DateTime StartTime { get; set; }
        public System.DateTime EndTime { get; set; }
        public bool IsPause { get; set; }
        public bool IsFinish { get; set; }
        public string Method { get; set; }
        public Nullable<decimal> Cost { get; set; }
        public string Note { get; set; }
        public Nullable<int> CreateBy { get; set; }
        public Nullable<System.DateTime> CreateAt { get; set; }
        public Nullable<int> UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdateAt { get; set; }
    
        public virtual ICollection<CustomerSurveyObject> CustomerSurveyObjects { get; set; }
        public virtual ICollection<CustomerSurveyQuestion> CustomerSurveyQuestions { get; set; }
    }
}
