//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iDAS.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerContactHistory
    {
        public CustomerContactHistory()
        {
            this.CustomerContactHistoryAttachmentFiles = new HashSet<CustomerContactHistoryAttachmentFile>();
        }
    
        public int ID { get; set; }
        public int CustomerID { get; set; }
        public int CustomerContactFormID { get; set; }
        public int EmployeeID { get; set; }
        public System.DateTime Time { get; set; }
        public string Requirment { get; set; }
        public Nullable<decimal> Cost { get; set; }
        public string Content { get; set; }
        public bool IsSuccess { get; set; }
        public string Note { get; set; }
        public bool IsPotential { get; set; }
        public bool IsOfficial { get; set; }
        public Nullable<int> CreateBy { get; set; }
        public Nullable<System.DateTime> CreateAt { get; set; }
        public Nullable<int> UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdateAt { get; set; }
    
        public virtual CustomerContactForm CustomerContactForm { get; set; }
        public virtual ICollection<CustomerContactHistoryAttachmentFile> CustomerContactHistoryAttachmentFiles { get; set; }
        public virtual Customer Customer { get; set; }
    }
}
