//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iDAS.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerContactCalendar
    {
        public int ID { get; set; }
        public int CustomerID { get; set; }
        public int CustomerContactFormID { get; set; }
        public bool IsNew { get; set; }
        public Nullable<System.DateTime> Time { get; set; }
        public Nullable<int> Content { get; set; }
        public string Note { get; set; }
        public Nullable<System.DateTime> CreateAt { get; set; }
        public Nullable<int> CreateBy { get; set; }
        public Nullable<System.DateTime> UpdateAt { get; set; }
        public Nullable<int> UpdateBy { get; set; }
    
        public virtual CustomerContactForm CustomerContactForm { get; set; }
        public virtual Customer Customer { get; set; }
    }
}
