//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iDAS.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class DispatchTo
    {
        public DispatchTo()
        {
            this.DispatchToAttachmentFiles = new HashSet<DispatchToAttachmentFile>();
            this.DispatchToCCs = new HashSet<DispatchToCC>();
            this.DispatchToDepartments = new HashSet<DispatchToDepartment>();
            this.DispatchToEmployees = new HashSet<DispatchToEmployee>();
            this.DispatchToTasks = new HashSet<DispatchToTask>();
        }
    
        public int ID { get; set; }
        public Nullable<int> DispatchCategoryID { get; set; }
        public Nullable<int> DispatchSecurityID { get; set; }
        public Nullable<int> DispatchUrgencyID { get; set; }
        public Nullable<int> DispatchMethodID { get; set; }
        public string Name { get; set; }
        public string Code { get; set; }
        public string Compendia { get; set; }
        public string NumberTo { get; set; }
        public bool FormHard { get; set; }
        public bool FormSoft { get; set; }
        public System.DateTime Date { get; set; }
        public string SendFrom { get; set; }
        public string SendTo { get; set; }
        public bool IsMoved { get; set; }
        public Nullable<System.DateTime> DateMoved { get; set; }
        public bool IsVerify { get; set; }
        public Nullable<System.DateTime> DateVerifyTime { get; set; }
        public string Note { get; set; }
        public string NoteMove { get; set; }
        public Nullable<System.DateTime> CreateAt { get; set; }
        public Nullable<int> CreateBy { get; set; }
        public Nullable<System.DateTime> UpdateAt { get; set; }
        public Nullable<int> UpdateBy { get; set; }
    
        public virtual DispatchCategory DispatchCategory { get; set; }
        public virtual DispatchMethod DispatchMethod { get; set; }
        public virtual DispatchSecurity DispatchSecurity { get; set; }
        public virtual ICollection<DispatchToAttachmentFile> DispatchToAttachmentFiles { get; set; }
        public virtual ICollection<DispatchToCC> DispatchToCCs { get; set; }
        public virtual ICollection<DispatchToDepartment> DispatchToDepartments { get; set; }
        public virtual ICollection<DispatchToEmployee> DispatchToEmployees { get; set; }
        public virtual DispatchUrgency DispatchUrgency { get; set; }
        public virtual ICollection<DispatchToTask> DispatchToTasks { get; set; }
    }
}
