//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iDAS.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class DispatchGoOutSide
    {
        public int ID { get; set; }
        public int DispatchGoID { get; set; }
        public string Name { get; set; }
        public string Position { get; set; }
        public string Company { get; set; }
        public bool Type { get; set; }
        public string Address { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Telephone { get; set; }
        public string PersonEmail { get; set; }
        public string Phone { get; set; }
        public string CompanyEmail { get; set; }
        public bool IsVerify { get; set; }
        public Nullable<System.DateTime> DateVerify { get; set; }
        public string NoteVerify { get; set; }
        public string Note { get; set; }
        public Nullable<System.DateTime> CreateAt { get; set; }
        public Nullable<int> CreateBy { get; set; }
        public Nullable<System.DateTime> UpdateAt { get; set; }
        public Nullable<int> UpdateBy { get; set; }
    
        public virtual DispatchGo DispatchGo { get; set; }
    }
}
