//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iDAS.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class DispatchGo
    {
        public DispatchGo()
        {
            this.DispatchGoAttachmentFiles = new HashSet<DispatchGoAttachmentFile>();
            this.DispatchGoCCs = new HashSet<DispatchGoCC>();
            this.DispatchGoDepartments = new HashSet<DispatchGoDepartment>();
            this.DispatchGoEmployees = new HashSet<DispatchGoEmployee>();
            this.DispatchGoOutSides = new HashSet<DispatchGoOutSide>();
            this.DispatchGoTasks = new HashSet<DispatchGoTask>();
        }
    
        public int ID { get; set; }
        public Nullable<int> DispatchCategoryID { get; set; }
        public Nullable<int> DispatchSecurityID { get; set; }
        public Nullable<int> DispatchUrgencyID { get; set; }
        public Nullable<int> DispatchMethodID { get; set; }
        public string Name { get; set; }
        public string Code { get; set; }
        public string Compendia { get; set; }
        public System.DateTime Date { get; set; }
        public bool Type { get; set; }
        public bool FormHard { get; set; }
        public bool FormSoft { get; set; }
        public string DestinationAddress { get; set; }
        public bool IsEdit { get; set; }
        public bool AlowNotAproval { get; set; }
        public bool IsApproval { get; set; }
        public bool IsAccept { get; set; }
        public Nullable<System.DateTime> ApprovalAt { get; set; }
        public Nullable<int> ApprovalBy { get; set; }
        public string ApprovalNote { get; set; }
        public bool IsMove { get; set; }
        public bool IsVerify { get; set; }
        public Nullable<System.DateTime> MoveAt { get; set; }
        public string NoteMove { get; set; }
        public string Note { get; set; }
        public Nullable<System.DateTime> CreateAt { get; set; }
        public Nullable<int> CreateBy { get; set; }
        public Nullable<System.DateTime> UpdateAt { get; set; }
        public Nullable<int> UpdateBy { get; set; }
    
        public virtual DispatchCategory DispatchCategory { get; set; }
        public virtual ICollection<DispatchGoAttachmentFile> DispatchGoAttachmentFiles { get; set; }
        public virtual ICollection<DispatchGoCC> DispatchGoCCs { get; set; }
        public virtual ICollection<DispatchGoDepartment> DispatchGoDepartments { get; set; }
        public virtual ICollection<DispatchGoEmployee> DispatchGoEmployees { get; set; }
        public virtual DispatchMethod DispatchMethod { get; set; }
        public virtual DispatchSecurity DispatchSecurity { get; set; }
        public virtual DispatchUrgency DispatchUrgency { get; set; }
        public virtual ICollection<DispatchGoOutSide> DispatchGoOutSides { get; set; }
        public virtual ICollection<DispatchGoTask> DispatchGoTasks { get; set; }
    }
}
