//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iDAS.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocumentRequirement
    {
        public int ID { get; set; }
        public Nullable<int> DocumentID { get; set; }
        public int DepartmentID { get; set; }
        public string Name { get; set; }
        public bool Type { get; set; }
        public bool IsEdit { get; set; }
        public bool IsApproval { get; set; }
        public bool IsAccept { get; set; }
        public Nullable<System.DateTime> ApprovalAt { get; set; }
        public Nullable<int> ApprovalBy { get; set; }
        public string ContentOld { get; set; }
        public string ContentChange { get; set; }
        public string ReasonChange { get; set; }
        public Nullable<System.DateTime> FinishDate { get; set; }
        public string Content { get; set; }
        public string Note { get; set; }
        public Nullable<System.DateTime> CreateAt { get; set; }
        public Nullable<int> CreateBy { get; set; }
        public Nullable<System.DateTime> UpdateAt { get; set; }
        public Nullable<int> UpdateBy { get; set; }
    
        public virtual Document Document { get; set; }
    }
}
