//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iDAS.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocumentDistribution
    {
        public int ID { get; set; }
        public int DocumentID { get; set; }
        public int DepartmentID { get; set; }
        public System.DateTime Date { get; set; }
        public int Number { get; set; }
        public bool FormH { get; set; }
        public bool FormS { get; set; }
        public Nullable<int> NumberObsolete { get; set; }
        public Nullable<System.DateTime> DateObsolote { get; set; }
        public Nullable<bool> FormHO { get; set; }
        public Nullable<bool> FormSO { get; set; }
        public string Note { get; set; }
        public string NoteObsolete { get; set; }
        public Nullable<int> IssuedBy { get; set; }
        public Nullable<int> ObsoleteBy { get; set; }
        public Nullable<System.DateTime> CreateAt { get; set; }
        public Nullable<int> CreateBy { get; set; }
        public Nullable<System.DateTime> UpdateAt { get; set; }
        public Nullable<int> UpdateBy { get; set; }
    
        public virtual Document Document { get; set; }
    }
}
