//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iDAS.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class Document
    {
        public Document()
        {
            this.DocumentAttachmentFiles = new HashSet<DocumentAttachmentFile>();
            this.DocumentAttachments = new HashSet<DocumentAttachment>();
            this.DocumentDistributions = new HashSet<DocumentDistribution>();
            this.DocumentRequirements = new HashSet<DocumentRequirement>();
            this.ProductDevelopmentRequirementPlanDocuments = new HashSet<ProductDevelopmentRequirementPlanDocument>();
        }
    
        public int ID { get; set; }
        public Nullable<int> DocumentCategoryID { get; set; }
        public int DocumentSecurityID { get; set; }
        public Nullable<int> DepartmentID { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public string Version { get; set; }
        public bool Type { get; set; }
        public bool FormH { get; set; }
        public bool FormS { get; set; }
        public bool IsEdit { get; set; }
        public bool IsApproval { get; set; }
        public bool IsAccept { get; set; }
        public bool IsPublic { get; set; }
        public bool IsDelete { get; set; }
        public bool IsObsolete { get; set; }
        public Nullable<System.DateTime> DateObsolete { get; set; }
        public Nullable<System.DateTime> ApprovalAt { get; set; }
        public Nullable<int> ApprovalBy { get; set; }
        public string ApprovalNote { get; set; }
        public Nullable<System.DateTime> PublicDate { get; set; }
        public Nullable<int> PublicNumber { get; set; }
        public Nullable<int> ParentID { get; set; }
        public string Content { get; set; }
        public string Note { get; set; }
        public string NoteIssued { get; set; }
        public Nullable<System.DateTime> CreateAt { get; set; }
        public Nullable<int> CreateBy { get; set; }
        public Nullable<System.DateTime> UpdateAt { get; set; }
        public Nullable<int> UpdateBy { get; set; }

        public bool AllUserAccess { get; set; }
        public Nullable<int> FolderID { get; set; }

        public bool QuickDownload { get; set; }
        public DateTime? DayDownloadLimited { get; set; }

        public virtual ICollection<DocumentAttachmentFile> DocumentAttachmentFiles { get; set; }
        public virtual ICollection<DocumentAttachment> DocumentAttachments { get; set; }
        public virtual DocumentCategory DocumentCategory { get; set; }
        public virtual ICollection<DocumentDistribution> DocumentDistributions { get; set; }
        public virtual ICollection<DocumentRequirement> DocumentRequirements { get; set; }
        public virtual DocumentSecurity DocumentSecurity { get; set; }
        public virtual ICollection<ProductDevelopmentRequirementPlanDocument> ProductDevelopmentRequirementPlanDocuments { get; set; }
    }
}
