//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iDAS.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class EquipmentCalibration
    {
        public EquipmentCalibration()
        {
            this.EquipmentMeasureCalibrations = new HashSet<EquipmentMeasureCalibration>();
        }
    
        public int ID { get; set; }
        public int EquipmentMeasureID { get; set; }
        public string AccreditationContent { get; set; }
        public Nullable<int> AccreditationPeriodic { get; set; }
        public Nullable<System.DateTime> AccreditationLastTime { get; set; }
        public Nullable<System.DateTime> AccreditationNextTime { get; set; }
        public string AccreditationBy { get; set; }
        public bool IsPass { get; set; }
        public Nullable<bool> Time { get; set; }
        public string Note { get; set; }
        public Nullable<int> CreateBy { get; set; }
        public Nullable<System.DateTime> CreateAt { get; set; }
        public Nullable<int> UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdateAt { get; set; }
    
        public virtual EquipmentMeasure EquipmentMeasure { get; set; }
        public virtual ICollection<EquipmentMeasureCalibration> EquipmentMeasureCalibrations { get; set; }
    }
}
