//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iDAS.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class EquipmentProductionHistory
    {
        public int ID { get; set; }
        public int EquipmentProductionID { get; set; }
        public Nullable<int> HumanDepartmentID { get; set; }
        public Nullable<int> HumanEmployeeID { get; set; }
        public System.DateTime Time { get; set; }
        public bool IsUsing { get; set; }
        public bool IsError { get; set; }
        public bool IsFixed { get; set; }
        public bool IsMaintain { get; set; }
        public bool IsCalibration { get; set; }
        public bool IsAccreditation { get; set; }
        public bool IsNotUse { get; set; }
        public string Note { get; set; }
        public Nullable<int> CreateBy { get; set; }
        public Nullable<System.DateTime> CreateAt { get; set; }
        public Nullable<int> UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdateAt { get; set; }
    
        public virtual HumanDepartment HumanDepartment { get; set; }
        public virtual HumanEmployee HumanEmployee { get; set; }
        public virtual EquipmentProduction EquipmentProduction { get; set; }
    }
}
