//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iDAS.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class EquipmentMeasure
    {
        public EquipmentMeasure()
        {
            this.EquipmentCalibrations = new HashSet<EquipmentCalibration>();
            this.EquipmentMeasureAttachmentFiles = new HashSet<EquipmentMeasureAttachmentFile>();
            this.EquipmentMeasureCalibrations = new HashSet<EquipmentMeasureCalibration>();
            this.EquipmentMeasureDepartments = new HashSet<EquipmentMeasureDepartment>();
        }
    
        public int ID { get; set; }
        public int EquipmentMeasureCategoryID { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public string SerialNumber { get; set; }
        public string MadeIn { get; set; }
        public Nullable<System.DateTime> MadeYear { get; set; }
        public Nullable<System.DateTime> UseStartTime { get; set; }
        public string Specifications { get; set; }
        public string Features { get; set; }
        public string SupportInfomation { get; set; }
        public Nullable<float> ScopeStart { get; set; }
        public Nullable<float> ScopeEnd { get; set; }
        public string ScopeUnit { get; set; }
        public Nullable<float> Accuracy { get; set; }
        public string CalibrationPeriodic { get; set; }
        public bool IsActive { get; set; }
        public bool IsDelete { get; set; }
        public bool IsUsing { get; set; }
        public bool IsError { get; set; }
        public bool IsFixed { get; set; }
        public bool IsCalibration { get; set; }
        public bool IsAccreditation { get; set; }
        public Nullable<System.DateTime> CalibrationLastTime { get; set; }
        public Nullable<System.DateTime> CalibrationNextTime { get; set; }
        public Nullable<System.DateTime> ExprireTime { get; set; }
        public Nullable<int> CreateBy { get; set; }
        public Nullable<System.DateTime> CreateAt { get; set; }
        public Nullable<int> UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdateAt { get; set; }
    
        public virtual ICollection<EquipmentCalibration> EquipmentCalibrations { get; set; }
        public virtual ICollection<EquipmentMeasureAttachmentFile> EquipmentMeasureAttachmentFiles { get; set; }
        public virtual ICollection<EquipmentMeasureCalibration> EquipmentMeasureCalibrations { get; set; }
        public virtual EquipmentMeasureCategory EquipmentMeasureCategory { get; set; }
        public virtual ICollection<EquipmentMeasureDepartment> EquipmentMeasureDepartments { get; set; }
    }
}
