//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iDAS.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class File
    {
        public File()
        {
            this.CustomerSystems = new HashSet<CustomerSystem>();
            this.Tutorials = new HashSet<Tutorial>();
        }
    
        public System.Guid ID { get; set; }
        public string Name { get; set; }
        public string Extension { get; set; }
        public double Size { get; set; }
        public string Type { get; set; }
        public byte[] Data { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<System.DateTime> CreateAt { get; set; }
        public Nullable<int> CreateBy { get; set; }
        public Nullable<System.DateTime> UpdateAt { get; set; }
        public Nullable<int> UpdateBy { get; set; }
    
        public virtual ICollection<CustomerSystem> CustomerSystems { get; set; }
        public virtual ICollection<Tutorial> Tutorials { get; set; }
    }
}
