//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iDAS.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class HumanRole
    {
        public HumanRole()
        {
            this.HumanAuditGradationRoles = new HashSet<HumanAuditGradationRole>();
            this.HumanOrganizations = new HashSet<HumanOrganization>();
            this.HumanPermissions = new HashSet<HumanPermission>();
            this.HumanRecruitmentCriterias = new HashSet<HumanRecruitmentCriteria>();
            this.HumanRecruitmentRequirements = new HashSet<HumanRecruitmentRequirement>();
            this.QualityNCRoles = new HashSet<QualityNCRole>();
        }
    
        public int ID { get; set; }
        public int HumanDepartmentID { get; set; }
        public string Name { get; set; }
        public bool IsActive { get; set; }
        public bool IsDelete { get; set; }
        public bool IsDestroy { get; set; }
        public Nullable<int> Position { get; set; }
        public string Resposibility { get; set; }
        public string Authorize { get; set; }
        public string Competence { get; set; }
        public string ReportTo { get; set; }
        public string ReplaceBy { get; set; }
        public string Note { get; set; }
        public Nullable<int> CreateBy { get; set; }
        public Nullable<System.DateTime> CreateAt { get; set; }
        public Nullable<int> UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdateAt { get; set; }
    
        public virtual ICollection<HumanAuditGradationRole> HumanAuditGradationRoles { get; set; }
        public virtual HumanDepartment HumanDepartment { get; set; }
        public virtual ICollection<HumanOrganization> HumanOrganizations { get; set; }
        public virtual ICollection<HumanPermission> HumanPermissions { get; set; }
        public virtual ICollection<HumanRecruitmentCriteria> HumanRecruitmentCriterias { get; set; }
        public virtual ICollection<HumanRecruitmentRequirement> HumanRecruitmentRequirements { get; set; }
        public virtual ICollection<QualityNCRole> QualityNCRoles { get; set; }
    }
}
