//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iDAS.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class HumanTrainingRequirement
    {
        public HumanTrainingRequirement()
        {
            this.HumanTrainingPlanRequirements = new HashSet<HumanTrainingPlanRequirement>();
            this.HumanTrainingRequirementEmployees = new HashSet<HumanTrainingRequirementEmployee>();
        }
    
        public int ID { get; set; }
        public int EmployeeID { get; set; }
        public Nullable<System.DateTime> StartTime { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
        public string Content { get; set; }
        public bool IsEdit { get; set; }
        public bool IsApproval { get; set; }
        public bool IsAccept { get; set; }
        public Nullable<System.DateTime> ApprovalAt { get; set; }
        public Nullable<int> ApprovalBy { get; set; }
        public string Note { get; set; }
        public Nullable<int> CreateBy { get; set; }
        public Nullable<System.DateTime> CreateAt { get; set; }
        public Nullable<int> UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdateAt { get; set; }
    
        public virtual ICollection<HumanTrainingPlanRequirement> HumanTrainingPlanRequirements { get; set; }
        public virtual ICollection<HumanTrainingRequirementEmployee> HumanTrainingRequirementEmployees { get; set; }
    }
}
