//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iDAS.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class HumanProfileWorkTrial
    {
        public HumanProfileWorkTrial()
        {
            this.HumanProfileWorkTrialResults = new HashSet<HumanProfileWorkTrialResult>();
        }
    
        public int ID { get; set; }
        public int HumanEmployeeID { get; set; }
        public Nullable<int> HumanRoleID { get; set; }
        public Nullable<System.DateTime> FromDate { get; set; }
        public Nullable<System.DateTime> ToDate { get; set; }
        public string Note { get; set; }
        public bool IsEdit { get; set; }
        public bool IsApproval { get; set; }
        public bool IsAccept { get; set; }
        public bool IsDelete { get; set; }
        public Nullable<System.DateTime> ApprovalAt { get; set; }
        public Nullable<int> ApprovalBy { get; set; }
        public string ApprovalNote { get; set; }
        public Nullable<int> CreateBy { get; set; }
        public Nullable<System.DateTime> CreateAt { get; set; }
        public Nullable<int> UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdateAt { get; set; }
        public Nullable<int> DirectorApproval { get; set; }
        public Nullable<System.DateTime> DirectorApprovalAt { get; set; }
        public Nullable<int> ContractType { get; set; }
        public Nullable<System.DateTime> ContractStartTime { get; set; }
        public Nullable<int> ManagerID { get; set; }
    
        public virtual HumanEmployee HumanEmployee { get; set; }
        public virtual ICollection<HumanProfileWorkTrialResult> HumanProfileWorkTrialResults { get; set; }
    }
}
