//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iDAS.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class HumanDepartment
    {
        public HumanDepartment()
        {
            this.CalendarCategories = new HashSet<CalendarCategory>();
            this.CustomerCategoryDepartments = new HashSet<CustomerCategoryDepartment>();
            this.DepartmentLegalAuditResults = new HashSet<DepartmentLegalAuditResult>();
            this.DepartmentRegulatoryAuditResults = new HashSet<DepartmentRegulatoryAuditResult>();
            this.DepartmentRequirmentAuditResults = new HashSet<DepartmentRequirmentAuditResult>();
            this.EquipmentMeasureDepartments = new HashSet<EquipmentMeasureDepartment>();
            this.EquipmentProductionDepartments = new HashSet<EquipmentProductionDepartment>();
            this.EquipmentProductionErrors = new HashSet<EquipmentProductionError>();
            this.EquipmentProductionHistories = new HashSet<EquipmentProductionHistory>();
            this.EquipmentProductionMaintains = new HashSet<EquipmentProductionMaintain>();
            this.HumanAuditDepartments = new HashSet<HumanAuditDepartment>();
            this.HumanRoles = new HashSet<HumanRole>();
            this.Tasks = new HashSet<Task>();
            this.ProductionCommands = new HashSet<ProductionCommand>();
            this.QualityAuditProgramDepartments = new HashSet<QualityAuditProgramDepartment>();
            this.QualityAuditProgramISOes = new HashSet<QualityAuditProgramISO>();
            this.QualityAuditRecordedVotes = new HashSet<QualityAuditRecordedVote>();
            this.QualityAuditResults = new HashSet<QualityAuditResult>();
            this.Risks = new HashSet<Risk>();
            this.TaskCalendars = new HashSet<TaskCalendar>();
            this.TaskRequests = new HashSet<TaskRequest>();
        }
    
        public int ID { get; set; }
        public int ParentID { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public string NameE { get; set; }
        public string Address { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public string Fax { get; set; }
        public string Tax { get; set; }
        public string Website { get; set; }
        public Nullable<System.DateTime> EstablishedDate { get; set; }
        public bool IsActive { get; set; }
        public bool IsDelete { get; set; }
        public bool IsCancel { get; set; }
        public bool IsMerge { get; set; }
        public bool IsDestroy { get; set; }
        public Nullable<int> Position { get; set; }
        public string History { get; set; }
        public string Resposibility { get; set; }
        public string Authorize { get; set; }
        public Nullable<int> CreateBy { get; set; }
        public Nullable<System.DateTime> CreateAt { get; set; }
        public Nullable<int> UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdateAt { get; set; }
    
        public virtual ICollection<CalendarCategory> CalendarCategories { get; set; }
        public virtual ICollection<CustomerCategoryDepartment> CustomerCategoryDepartments { get; set; }
        public virtual ICollection<DepartmentLegalAuditResult> DepartmentLegalAuditResults { get; set; }
        public virtual ICollection<DepartmentRegulatoryAuditResult> DepartmentRegulatoryAuditResults { get; set; }
        public virtual ICollection<DepartmentRequirmentAuditResult> DepartmentRequirmentAuditResults { get; set; }
        public virtual ICollection<EquipmentMeasureDepartment> EquipmentMeasureDepartments { get; set; }
        public virtual ICollection<EquipmentProductionDepartment> EquipmentProductionDepartments { get; set; }
        public virtual ICollection<EquipmentProductionError> EquipmentProductionErrors { get; set; }
        public virtual ICollection<EquipmentProductionHistory> EquipmentProductionHistories { get; set; }
        public virtual ICollection<EquipmentProductionMaintain> EquipmentProductionMaintains { get; set; }
        public virtual ICollection<HumanAuditDepartment> HumanAuditDepartments { get; set; }
        public virtual ICollection<HumanRole> HumanRoles { get; set; }
        public virtual ICollection<Task> Tasks { get; set; }
        public virtual ICollection<ProductionCommand> ProductionCommands { get; set; }
        public virtual ICollection<QualityAuditProgramDepartment> QualityAuditProgramDepartments { get; set; }
        public virtual ICollection<QualityAuditProgramISO> QualityAuditProgramISOes { get; set; }
        public virtual ICollection<QualityAuditRecordedVote> QualityAuditRecordedVotes { get; set; }
        public virtual ICollection<QualityAuditResult> QualityAuditResults { get; set; }
        public virtual ICollection<Risk> Risks { get; set; }
        public virtual ICollection<TaskCalendar> TaskCalendars { get; set; }
        public virtual ICollection<TaskRequest> TaskRequests { get; set; }
    }
}
