//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iDAS.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class HumanTrainingPlanDetail
    {
        public HumanTrainingPlanDetail()
        {
            this.HumanTrainingPractioners = new HashSet<HumanTrainingPractioner>();
        }
    
        public int ID { get; set; }
        public int HumanTrainingPlanID { get; set; }
        public string Content { get; set; }
        public int Number { get; set; }
        public string Reason { get; set; }
        public bool Type { get; set; }
        public Nullable<decimal> ExpectedCost { get; set; }
        public string Certificate { get; set; }
        public string Note { get; set; }
        public Nullable<bool> IsCommit { get; set; }
        public string CommitContent { get; set; }
        public System.DateTime FromDate { get; set; }
        public System.DateTime ToDate { get; set; }
        public string Address { get; set; }
        public bool IsCancel { get; set; }
        public string ReasonCancel { get; set; }
        public Nullable<int> CreateBy { get; set; }
        public Nullable<System.DateTime> CreateAt { get; set; }
        public Nullable<int> UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdateAt { get; set; }
    
        public virtual HumanTrainingPlan HumanTrainingPlan { get; set; }
        public virtual ICollection<HumanTrainingPractioner> HumanTrainingPractioners { get; set; }
    }
}
