//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iDAS.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class HumanRecruitmentInterview
    {
        public int ID { get; set; }
        public int HumanRecruitmentProfileInterviewID { get; set; }
        public int HumanRecruitmentPlanInterviewID { get; set; }
        public string Result { get; set; }
        public System.DateTime Time { get; set; }
        public string Note { get; set; }
        public Nullable<System.DateTime> CreateAt { get; set; }
        public Nullable<int> CreateBy { get; set; }
        public Nullable<System.DateTime> UpdateAt { get; set; }
        public Nullable<int> UpdateBy { get; set; }
    
        public virtual HumanRecruitmentPlanInterview HumanRecruitmentPlanInterview { get; set; }
        public virtual HumanRecruitmentProfileInterview HumanRecruitmentProfileInterview { get; set; }
    }
}
