//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iDAS.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class HumanAuditTick
    {
        public HumanAuditTick()
        {
            this.HumanAuditTickResultBonusScores = new HashSet<HumanAuditTickResultBonusScore>();
            this.HumanAuditTickResults = new HashSet<HumanAuditTickResult>();
        }
    
        public int ID { get; set; }
        public int HumanAuditGradationRoleID { get; set; }
        public int HumanEmployeeID { get; set; }
        public bool IsEmployeeAuditted { get; set; }
        public Nullable<System.DateTime> Time { get; set; }
        public decimal EmployeeAuditResult { get; set; }
        public decimal EmployeeAuditManagementResult { get; set; }
        public decimal EmployeeAuditLeaderResult { get; set; }
        public bool IsManagementAuditted { get; set; }
        public bool IsLeaderAuditted { get; set; }
        public Nullable<int> HumanAuditLevelID { get; set; }
        public string Comments { get; set; }
        public bool IsSave { get; set; }
        public Nullable<System.DateTime> CreateAt { get; set; }
        public Nullable<int> CreateBy { get; set; }
        public Nullable<System.DateTime> UpdateAt { get; set; }
        public Nullable<int> UpdateBy { get; set; }
    
        public virtual HumanAuditGradationRole HumanAuditGradationRole { get; set; }
        public virtual HumanAuditLevel HumanAuditLevel { get; set; }
        public virtual ICollection<HumanAuditTickResultBonusScore> HumanAuditTickResultBonusScores { get; set; }
        public virtual ICollection<HumanAuditTickResult> HumanAuditTickResults { get; set; }
        public virtual HumanEmployee HumanEmployee { get; set; }
    }
}
