//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iDAS.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class HumanPhaseAudit
    {
        public HumanPhaseAudit()
        {
            this.HumanEmployeeAudits = new HashSet<HumanEmployeeAudit>();
        }
    
        public int ID { get; set; }
        public int HumanCategoryQuestionID { get; set; }
        public string Name { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public string Contents { get; set; }
        public int NumberSendInDay { get; set; }
        public bool IsEdit { get; set; }
        public bool IsApproval { get; set; }
        public bool IsAccept { get; set; }
        public bool IsDelete { get; set; }
        public Nullable<int> ApprovalBy { get; set; }
        public Nullable<System.DateTime> ApprovalAt { get; set; }
        public string ApprovalNote { get; set; }
        public Nullable<System.DateTime> CreateAt { get; set; }
        public Nullable<int> CreateBy { get; set; }
        public Nullable<System.DateTime> UpdateAt { get; set; }
        public Nullable<int> UpdateBy { get; set; }
    
        public virtual HumanCategoryQuestion HumanCategoryQuestion { get; set; }
        public virtual ICollection<HumanEmployeeAudit> HumanEmployeeAudits { get; set; }
    }
}
