//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iDAS.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class HumanRecruitmentProfileResult
    {
        public int ID { get; set; }
        public int HumanRecruitmentProfileInterviewID { get; set; }
        public int TotalPoint { get; set; }
        public System.DateTime StartTime { get; set; }
        public decimal Salary { get; set; }
        public bool IsApproval { get; set; }
        public bool IsPass { get; set; }
        public Nullable<int> ApprovalBy { get; set; }
        public Nullable<System.DateTime> ApprovalAt { get; set; }
        public string Note { get; set; }
        public Nullable<System.DateTime> CreateAt { get; set; }
        public Nullable<int> CreateBy { get; set; }
        public Nullable<System.DateTime> UpdateAt { get; set; }
        public Nullable<int> UpdateBy { get; set; }
    
        public virtual HumanRecruitmentProfileInterview HumanRecruitmentProfileInterview { get; set; }
    }
}
