//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iDAS.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class HumanRecruitmentProfile
    {
        public HumanRecruitmentProfile()
        {
            this.HumanRecruitmentProfileInterviews = new HashSet<HumanRecruitmentProfileInterview>();
            this.HumanRecruitmentReviews = new HashSet<HumanRecruitmentReview>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public string Avatar { get; set; }
        public string Address { get; set; }
        public Nullable<System.DateTime> Birthday { get; set; }
        public bool Gender { get; set; }
        public string Nationality { get; set; }
        public string People { get; set; }
        public string Religion { get; set; }
        public string PlaceOfBirth { get; set; }
        public string NumberOfIdentityCard { get; set; }
        public Nullable<System.DateTime> DateIssueOfIdentityCard { get; set; }
        public string PlaceIssueOfIdentityCard { get; set; }
        public string HomePhone { get; set; }
        public string PlaceOfTranning { get; set; }
        public string Specicalization { get; set; }
        public string LevelOfComputerization { get; set; }
        public string ForeignLanguage { get; set; }
        public string Literacy { get; set; }
        public string Qualifications { get; set; }
        public string ListOfCertificates { get; set; }
        public string Experience { get; set; }
        public Nullable<decimal> Salary { get; set; }
        public Nullable<short> YearsOfExperience { get; set; }
        public bool IsEmployee { get; set; }
        public bool IsDelete { get; set; }
        public Nullable<int> CreateBy { get; set; }
        public Nullable<System.DateTime> CreateAt { get; set; }
        public Nullable<int> UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdateAt { get; set; }
        public int EmployeeID { get; set; }
    
        public virtual ICollection<HumanRecruitmentProfileInterview> HumanRecruitmentProfileInterviews { get; set; }
        public virtual ICollection<HumanRecruitmentReview> HumanRecruitmentReviews { get; set; }
    }
}
