//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iDAS.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class HumanCategoryQuestion
    {
        public HumanCategoryQuestion()
        {
            this.HumanPhaseAudits = new HashSet<HumanPhaseAudit>();
            this.HumanQuestions = new HashSet<HumanQuestion>();
        }
    
        public int ID { get; set; }
        public int ParentID { get; set; }
        public string Name { get; set; }
        public string Note { get; set; }
        public bool IsUse { get; set; }
        public bool IsDelete { get; set; }
        public Nullable<System.DateTime> CreateAt { get; set; }
        public Nullable<int> CreateBy { get; set; }
        public Nullable<System.DateTime> UpdateAt { get; set; }
        public Nullable<int> UpdateBy { get; set; }
    
        public virtual ICollection<HumanPhaseAudit> HumanPhaseAudits { get; set; }
        public virtual ICollection<HumanQuestion> HumanQuestions { get; set; }
    }
}
