//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iDAS.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class HumanRecruitmentCriteria
    {
        public HumanRecruitmentCriteria()
        {
            this.HumanRecruitmentReviews = new HashSet<HumanRecruitmentReview>();
        }
    
        public int ID { get; set; }
        public int HumanRoleID { get; set; }
        public string Name { get; set; }
        public string Content { get; set; }
        public bool IsActive { get; set; }
        public bool IsDelete { get; set; }
        public int MinPoint { get; set; }
        public int MaxPoint { get; set; }
        public int Factor { get; set; }
        public Nullable<int> CreateBy { get; set; }
        public Nullable<System.DateTime> CreateAt { get; set; }
        public Nullable<int> UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdateAt { get; set; }
    
        public virtual HumanRole HumanRole { get; set; }
        public virtual ICollection<HumanRecruitmentReview> HumanRecruitmentReviews { get; set; }
    }
}
