//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iDAS.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class HumanProfileWorkTrialResult
    {
        public int ID { get; set; }
        public int HumanProfileWorkTrialID { get; set; }
        public int QualityCriteriaID { get; set; }
        public Nullable<int> EmployeePoint { get; set; }
        public Nullable<int> ManagerPoint { get; set; }
        public Nullable<System.DateTime> CreateAt { get; set; }
        public Nullable<int> CreateBy { get; set; }
        public Nullable<System.DateTime> UpdateAt { get; set; }
        public Nullable<int> UpdateBy { get; set; }
        public string Note { get; set; }
    
        public virtual HumanProfileWorkTrial HumanProfileWorkTrial { get; set; }
        public virtual QualityCriteria QualityCriteria { get; set; }
    }
}
