//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iDAS.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class HumanAuditCriteria
    {
        public HumanAuditCriteria()
        {
            this.HumanAuditCriteriaPoints = new HashSet<HumanAuditCriteriaPoint>();
        }
    
        public int ID { get; set; }
        public int HumanAuditCriteriaCategoryID { get; set; }
        public string Name { get; set; }
        public string Note { get; set; }
        public Nullable<System.DateTime> CreateAt { get; set; }
        public int Factory { get; set; }
        public Nullable<int> CreateBy { get; set; }
        public Nullable<System.DateTime> UpdateAt { get; set; }
        public Nullable<int> UpdateBy { get; set; }
    
        public virtual HumanAuditCriteriaCategory HumanAuditCriteriaCategory { get; set; }
        public virtual ICollection<HumanAuditCriteriaPoint> HumanAuditCriteriaPoints { get; set; }
    }
}
