//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iDAS.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class HumanTrainingPractioner
    {
        public int ID { get; set; }
        public Nullable<int> Rank { get; set; }
        public bool IsRegister { get; set; }
        public bool IsAcceptCommit { get; set; }
        public System.DateTime TimeRegister { get; set; }
        public bool IsJoin { get; set; }
        public string ResonUnJoin { get; set; }
        public Nullable<int> NumberPresence { get; set; }
        public Nullable<int> NumberAbsence { get; set; }
        public Nullable<decimal> TotalPoint { get; set; }
        public string CommentOfTeacher { get; set; }
        public bool IsInProfile { get; set; }
        public Nullable<System.DateTime> UpdateAt { get; set; }
        public Nullable<int> CreateBy { get; set; }
        public Nullable<System.DateTime> CreateAt { get; set; }
        public Nullable<int> UpdateBy { get; set; }
        public int HumanTrainingPlanDetailID { get; set; }
        public int HumanEmployeeID { get; set; }
    
        public virtual HumanEmployee HumanEmployee { get; set; }
        public virtual HumanTrainingPlanDetail HumanTrainingPlanDetail { get; set; }
    }
}
