//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iDAS.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class HumanResultQuestion
    {
        public HumanResultQuestion()
        {
            this.HumanResultAnswers = new HashSet<HumanResultAnswer>();
        }
    
        public int ID { get; set; }
        public int HumanEmployeeAuditID { get; set; }
        public int HumanQuestionID { get; set; }
        public bool IsResult { get; set; }
        public Nullable<System.DateTime> CreateAt { get; set; }
        public Nullable<int> CreateBy { get; set; }
        public Nullable<System.DateTime> UpdateAt { get; set; }
        public Nullable<int> UpdateBy { get; set; }
    
        public virtual HumanEmployeeAudit HumanEmployeeAudit { get; set; }
        public virtual HumanQuestion HumanQuestion { get; set; }
        public virtual ICollection<HumanResultAnswer> HumanResultAnswers { get; set; }
    }
}
