//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iDAS.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class HumanAuditGradationRole
    {
        public HumanAuditGradationRole()
        {
            this.HumanAuditGradationCriterias = new HashSet<HumanAuditGradationCriteria>();
            this.HumanAuditLevels = new HashSet<HumanAuditLevel>();
            this.HumanAuditTicks = new HashSet<HumanAuditTick>();
        }
    
        public int ID { get; set; }
        public int HumanAuditDepartmentID { get; set; }
        public int HumanRoleID { get; set; }
        public int Factory { get; set; }
        public bool IsAudit { get; set; }
        public Nullable<System.DateTime> CreateAt { get; set; }
        public Nullable<int> CreateBy { get; set; }
        public Nullable<System.DateTime> UpdateAt { get; set; }
        public Nullable<int> UpdateBy { get; set; }
    
        public virtual HumanAuditDepartment HumanAuditDepartment { get; set; }
        public virtual ICollection<HumanAuditGradationCriteria> HumanAuditGradationCriterias { get; set; }
        public virtual HumanRole HumanRole { get; set; }
        public virtual ICollection<HumanAuditLevel> HumanAuditLevels { get; set; }
        public virtual ICollection<HumanAuditTick> HumanAuditTicks { get; set; }
    }
}
