//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iDAS.Base
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class iDASCenterEntities : DbContext
    {
        public iDASCenterEntities()
            : base("name=iDASCenterEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CenterAction> CenterActions { get; set; }
        public virtual DbSet<CenterFunction> CenterFunctions { get; set; }
        public virtual DbSet<CenterModule> CenterModules { get; set; }
        public virtual DbSet<CenterRiskCategory> CenterRiskCategories { get; set; }
        public virtual DbSet<CenterRiskMethod> CenterRiskMethods { get; set; }
        public virtual DbSet<CenterRisk> CenterRisks { get; set; }
        public virtual DbSet<CenterRiskTreatment> CenterRiskTreatments { get; set; }
        public virtual DbSet<CenterSystem> CenterSystems { get; set; }
        public virtual DbSet<CustomerSystemModule> CustomerSystemModules { get; set; }
        public virtual DbSet<CustomerSystem> CustomerSystems { get; set; }
        public virtual DbSet<File> Files { get; set; }
        public virtual DbSet<ISOControl> ISOControls { get; set; }
        public virtual DbSet<ISOIndexCriteria> ISOIndexCriterias { get; set; }
        public virtual DbSet<ISOIndex> ISOIndexes { get; set; }
        public virtual DbSet<ISOIndexModule> ISOIndexModules { get; set; }
        public virtual DbSet<ISOMeeting> ISOMeetings { get; set; }
        public virtual DbSet<ISOStandardLibrary> ISOStandardLibraries { get; set; }
        public virtual DbSet<ISOStandardModule> ISOStandardModules { get; set; }
        public virtual DbSet<ISOStandard> ISOStandards { get; set; }
        public virtual DbSet<Tutorial> Tutorials { get; set; }
        public virtual DbSet<CenterDepartmentRequirmentAttachment> CenterDepartmentRequirmentAttachments { get; set; }
        public virtual DbSet<CenterDepartmentRequirmentCategory> CenterDepartmentRequirmentCategories { get; set; }
        public virtual DbSet<CenterDepartmentRequirment> CenterDepartmentRequirments { get; set; }
        public virtual DbSet<CenterAuditAnswer> CenterAuditAnswers { get; set; }
        public virtual DbSet<CenterAuditCategoryQuestion> CenterAuditCategoryQuestions { get; set; }
        public virtual DbSet<CenterAuditQuestion> CenterAuditQuestions { get; set; }
        public virtual DbSet<CenterKPICriteriaCategory> CenterKPICriteriaCategories { get; set; }
        public virtual DbSet<CenterKPICriteriaPoint> CenterKPICriteriaPoints { get; set; }
        public virtual DbSet<CenterKPICriteria> CenterKPICriterias { get; set; }
        public virtual DbSet<ISONaceCode> ISONaceCodes { get; set; }
        public virtual DbSet<ISOIndexFunction> ISOIndexFunctions { get; set; }
    }
}
