//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iDAS.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class ISOStandardModule
    {
        public int ID { get; set; }
        public int ISOStandardID { get; set; }
        public Nullable<int> CenterModuleID { get; set; }
        public bool IsActive { get; set; }
        public bool IsShow { get; set; }
        public bool IsRequired { get; set; }
        public Nullable<System.DateTime> UpdateAt { get; set; }
        public Nullable<int> UpdateBy { get; set; }
    
        public virtual CenterModule CenterModule { get; set; }
        public virtual ISOStandard ISOStandard { get; set; }
    }
}
