//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iDAS.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductionRequirement
    {
        public ProductionRequirement()
        {
            this.ProductDevelopmentRequirementPlans = new HashSet<ProductDevelopmentRequirementPlan>();
            this.ProductionCommands = new HashSet<ProductionCommand>();
            this.ProductionPlans = new HashSet<ProductionPlan>();
        }
    
        public int ID { get; set; }
        public int HumanEmployeeID { get; set; }
        public Nullable<int> ProductionLevelID { get; set; }
        public int StockProductID { get; set; }
        public int Quantity { get; set; }
        public System.DateTime EndTime { get; set; }
        public Nullable<System.DateTime> FinishTime { get; set; }
        public bool IsNew { get; set; }
        public bool IsPause { get; set; }
        public bool IsFinish { get; set; }
        public bool IsDelete { get; set; }
        public string Note { get; set; }
        public Nullable<System.DateTime> CreateAt { get; set; }
        public Nullable<int> CreateBy { get; set; }
        public Nullable<System.DateTime> UpdateAt { get; set; }
        public Nullable<int> UpdateBy { get; set; }
    
        public virtual ICollection<ProductDevelopmentRequirementPlan> ProductDevelopmentRequirementPlans { get; set; }
        public virtual ICollection<ProductionCommand> ProductionCommands { get; set; }
        public virtual ProductionLevel ProductionLevel { get; set; }
        public virtual ICollection<ProductionPlan> ProductionPlans { get; set; }
        public virtual StockProduct StockProduct { get; set; }
    }
}
