//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iDAS.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductionCommand
    {
        public ProductionCommand()
        {
            this.ProductionPerforms = new HashSet<ProductionPerform>();
        }
    
        public int ID { get; set; }
        public string Code { get; set; }
        public string BatchCode { get; set; }
        public Nullable<int> ProductionPlanID { get; set; }
        public Nullable<int> ProductionRequirementID { get; set; }
        public int ProductionStageID { get; set; }
        public int HumanDepartmentID { get; set; }
        public int Quantity { get; set; }
        public System.DateTime StartTime { get; set; }
        public System.DateTime EndTime { get; set; }
        public Nullable<System.DateTime> FinishTime { get; set; }
        public bool IsStart { get; set; }
        public bool IsPause { get; set; }
        public bool IsFinish { get; set; }
        public bool IsDelete { get; set; }
        public string Note { get; set; }
        public Nullable<System.DateTime> CreateAt { get; set; }
        public Nullable<int> CreateBy { get; set; }
        public Nullable<System.DateTime> UpdateAt { get; set; }
        public Nullable<int> UpdateBy { get; set; }
    
        public virtual HumanDepartment HumanDepartment { get; set; }
        public virtual ProductionPlan ProductionPlan { get; set; }
        public virtual ProductionRequirement ProductionRequirement { get; set; }
        public virtual ProductionStage ProductionStage { get; set; }
        public virtual ICollection<ProductionPerform> ProductionPerforms { get; set; }
    }
}
