//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iDAS.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductionPlan
    {
        public ProductionPlan()
        {
            this.ProductionCommands = new HashSet<ProductionCommand>();
            this.ProductionPlanEquipments = new HashSet<ProductionPlanEquipment>();
            this.ProductionPlanMaterials = new HashSet<ProductionPlanMaterial>();
            this.ProductionPlanProducts = new HashSet<ProductionPlanProduct>();
        }
    
        public int ID { get; set; }
        public int ProductionRequirementID { get; set; }
        public float Quantity { get; set; }
        public System.DateTime StartTime { get; set; }
        public System.DateTime EndTime { get; set; }
        public bool IsDelete { get; set; }
        public string Note { get; set; }
        public Nullable<System.DateTime> CreateAt { get; set; }
        public Nullable<int> CreateBy { get; set; }
        public Nullable<System.DateTime> UpdateAt { get; set; }
        public Nullable<int> UpdateBy { get; set; }
    
        public virtual ICollection<ProductionCommand> ProductionCommands { get; set; }
        public virtual ICollection<ProductionPlanEquipment> ProductionPlanEquipments { get; set; }
        public virtual ICollection<ProductionPlanMaterial> ProductionPlanMaterials { get; set; }
        public virtual ICollection<ProductionPlanProduct> ProductionPlanProducts { get; set; }
        public virtual ProductionRequirement ProductionRequirement { get; set; }
    }
}
