//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iDAS.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductionPerformResult
    {
        public int ID { get; set; }
        public int HumanEmployeeID { get; set; }
        public int ProductionPerformID { get; set; }
        public bool IsAbsent { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<int> StockProductID { get; set; }
        public Nullable<float> MaterialNumber { get; set; }
        public Nullable<float> MaterialExitsNumber { get; set; }
        public Nullable<int> ProductionPerformProductResultID { get; set; }
        public string Cause { get; set; }
        public string Solution { get; set; }
        public string Note { get; set; }
        public Nullable<System.DateTime> CreateAt { get; set; }
        public Nullable<int> CreateBy { get; set; }
        public Nullable<System.DateTime> UpdateAt { get; set; }
        public Nullable<int> UpdateBy { get; set; }
    
        public virtual ProductionPerform ProductionPerform { get; set; }
    }
}
