//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iDAS.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductDevelopmentRequirementPlan
    {
        public ProductDevelopmentRequirementPlan()
        {
            this.ProductDevelopmentRequirementPlanDocuments = new HashSet<ProductDevelopmentRequirementPlanDocument>();
        }
    
        public int ID { get; set; }
        public int QualityPlanID { get; set; }
        public Nullable<int> ProductDevelopmentRequirementID { get; set; }
        public Nullable<int> ProductionRequirementID { get; set; }
        public Nullable<System.DateTime> CreateAt { get; set; }
        public Nullable<int> CreateBy { get; set; }
        public Nullable<System.DateTime> UpdateAt { get; set; }
        public int UpdateBy { get; set; }
    
        public virtual ICollection<ProductDevelopmentRequirementPlanDocument> ProductDevelopmentRequirementPlanDocuments { get; set; }
        public virtual ProductDevelopmentRequirement ProductDevelopmentRequirement { get; set; }
        public virtual QualityPlan QualityPlan { get; set; }
        public virtual ProductionRequirement ProductionRequirement { get; set; }
    }
}
