//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iDAS.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductionStage
    {
        public ProductionStage()
        {
            this.ProductionCommands = new HashSet<ProductionCommand>();
            this.ProductionStageCriteriaCategories = new HashSet<ProductionStageCriteriaCategory>();
            this.ProductionStageEquipments = new HashSet<ProductionStageEquipment>();
            this.ProductionStageMaterials = new HashSet<ProductionStageMaterial>();
            this.ProductionStageProducts = new HashSet<ProductionStageProduct>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public int StockProductID { get; set; }
        public int ResultProductID { get; set; }
        public int Quantity { get; set; }
        public Nullable<float> ResultQuantity { get; set; }
        public Nullable<float> MenDay { get; set; }
        public bool IsActive { get; set; }
        public bool IsDelete { get; set; }
        public int Position { get; set; }
        public string Note { get; set; }
        public Nullable<System.DateTime> CreateAt { get; set; }
        public Nullable<int> CreateBy { get; set; }
        public Nullable<System.DateTime> UpdateAt { get; set; }
        public Nullable<int> UpdateBy { get; set; }
    
        public virtual ICollection<ProductionCommand> ProductionCommands { get; set; }
        public virtual ICollection<ProductionStageCriteriaCategory> ProductionStageCriteriaCategories { get; set; }
        public virtual ICollection<ProductionStageEquipment> ProductionStageEquipments { get; set; }
        public virtual ICollection<ProductionStageMaterial> ProductionStageMaterials { get; set; }
        public virtual ICollection<ProductionStageProduct> ProductionStageProducts { get; set; }
        public virtual StockProduct StockProduct { get; set; }
    }
}
