//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iDAS.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class Profile
    {
        public Profile()
        {
            this.ProfileAttachmentFiles = new HashSet<ProfileAttachmentFile>();
            this.ProfileBorrows = new HashSet<ProfileBorrow>();
            this.ProfileCancelProfiles = new HashSet<ProfileCancelProfile>();
        }
    
        public int ID { get; set; }
        public int ProfileCategoryID { get; set; }
        public int ProfileSecurityID { get; set; }
        public int EmployeeID { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public bool FormH { get; set; }
        public bool FormS { get; set; }
        public Nullable<System.DateTime> ReceivedAt { get; set; }
        public Nullable<System.DateTime> NotUseAt { get; set; }
        public Nullable<int> StoreTime { get; set; }
        public Nullable<int> StoreRoomTime { get; set; }
        public string StoreRoomPosition { get; set; }
        public string Note { get; set; }
        public bool IsUse { get; set; }
        public bool IsDelete { get; set; }
        public Nullable<System.DateTime> CreateAt { get; set; }
        public Nullable<int> CreateBy { get; set; }
        public Nullable<System.DateTime> UpdateAt { get; set; }
        public Nullable<int> UpdateBy { get; set; }
    
        public virtual ICollection<ProfileAttachmentFile> ProfileAttachmentFiles { get; set; }
        public virtual ICollection<ProfileBorrow> ProfileBorrows { get; set; }
        public virtual ICollection<ProfileCancelProfile> ProfileCancelProfiles { get; set; }
        public virtual ProfileCategory ProfileCategory { get; set; }
        public virtual ProfileSecurity ProfileSecurity { get; set; }
    }
}
