//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iDAS.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class QualityCriteriaCategory
    {
        public QualityCriteriaCategory()
        {
            this.Audits = new HashSet<Audit>();
            this.ProductionStageCriteriaCategories = new HashSet<ProductionStageCriteriaCategory>();
            this.QualityCriterias = new HashSet<QualityCriteria>();
        }
    
        public int ID { get; set; }
        public Nullable<int> EmployeeID { get; set; }
        public string Name { get; set; }
        public bool IsActive { get; set; }
        public bool IsDelete { get; set; }
        public bool IsProduction { get; set; }
        public Nullable<int> ParentID { get; set; }
        public string Note { get; set; }
        public Nullable<System.DateTime> CreateAt { get; set; }
        public Nullable<int> CreateBy { get; set; }
        public Nullable<System.DateTime> UpdateAt { get; set; }
        public Nullable<int> UpdateBy { get; set; }
    
        public virtual ICollection<Audit> Audits { get; set; }
        public virtual ICollection<ProductionStageCriteriaCategory> ProductionStageCriteriaCategories { get; set; }
        public virtual ICollection<QualityCriteria> QualityCriterias { get; set; }
    }
}
