//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iDAS.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class QualityMeeting
    {
        public QualityMeeting()
        {
            this.QualityMeetingAttachmentFiles = new HashSet<QualityMeetingAttachmentFile>();
            this.QualityMeetingObjects = new HashSet<QualityMeetingObject>();
            this.QualityMeetingProblems = new HashSet<QualityMeetingProblem>();
            this.QualityMeetingResults = new HashSet<QualityMeetingResult>();
        }
    
        public int ID { get; set; }
        public int DepartmentID { get; set; }
        public string Name { get; set; }
        public System.DateTime StartTime { get; set; }
        public System.DateTime EndTime { get; set; }
        public decimal Cost { get; set; }
        public bool IsNew { get; set; }
        public bool IsEdit { get; set; }
        public bool IsApproval { get; set; }
        public bool IsAccept { get; set; }
        public bool IsFinish { get; set; }
        public string Address { get; set; }
        public string TaskPrepare { get; set; }
        public Nullable<System.DateTime> ApprovalAt { get; set; }
        public Nullable<int> ApprovalBy { get; set; }
        public string Content { get; set; }
        public string Note { get; set; }
        public Nullable<System.DateTime> CreateAt { get; set; }
        public Nullable<int> CreateBy { get; set; }
        public Nullable<System.DateTime> UpdateAt { get; set; }
        public Nullable<int> UpdateBy { get; set; }
    
        public virtual ICollection<QualityMeetingAttachmentFile> QualityMeetingAttachmentFiles { get; set; }
        public virtual ICollection<QualityMeetingObject> QualityMeetingObjects { get; set; }
        public virtual ICollection<QualityMeetingProblem> QualityMeetingProblems { get; set; }
        public virtual ICollection<QualityMeetingResult> QualityMeetingResults { get; set; }
    }
}
