//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iDAS.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class QualityNC
    {
        public QualityNC()
        {
            this.AuditResults = new HashSet<AuditResult>();
            this.DepartmentLegalAuditResults = new HashSet<DepartmentLegalAuditResult>();
            this.DepartmentRegulatoryAuditResults = new HashSet<DepartmentRegulatoryAuditResult>();
            this.DepartmentRequirmentAuditResults = new HashSet<DepartmentRequirmentAuditResult>();
            this.QualityAuditResults = new HashSet<QualityAuditResult>();
            this.QualityCAPARequirements = new HashSet<QualityCAPARequirement>();
            this.QualityNCEmployees = new HashSet<QualityNCEmployee>();
            this.QualityNCRoles = new HashSet<QualityNCRole>();
            this.QualityNCTasks = new HashSet<QualityNCTask>();
            this.QualityNCStockAdjustments = new HashSet<QualityNCStockAdjustment>();
            this.RiskAudits = new HashSet<RiskAudit>();
        }
    
        public int ID { get; set; }
        public int DepartmentID { get; set; }
        public string Source { get; set; }
        public System.DateTime Time { get; set; }
        public string Content { get; set; }
        public bool IsMaximum { get; set; }
        public bool IsMedium { get; set; }
        public bool IsObs { get; set; }
        public bool IsVerify { get; set; }
        public bool IsTrue { get; set; }
        public bool IsCompleteAuto { get; set; }
        public bool IsComplete { get; set; }
        public bool IsCAPA { get; set; }
        public bool IsLock { get; set; }
        public Nullable<System.DateTime> CheckAt { get; set; }
        public string CheckNote { get; set; }
        public Nullable<System.DateTime> CreateAt { get; set; }
        public Nullable<int> CreateBy { get; set; }
        public Nullable<System.DateTime> UpdateAt { get; set; }
        public Nullable<int> UpdateBy { get; set; }
    
        public virtual ICollection<AuditResult> AuditResults { get; set; }
        public virtual ICollection<DepartmentLegalAuditResult> DepartmentLegalAuditResults { get; set; }
        public virtual ICollection<DepartmentRegulatoryAuditResult> DepartmentRegulatoryAuditResults { get; set; }
        public virtual ICollection<DepartmentRequirmentAuditResult> DepartmentRequirmentAuditResults { get; set; }
        public virtual ICollection<QualityAuditResult> QualityAuditResults { get; set; }
        public virtual ICollection<QualityCAPARequirement> QualityCAPARequirements { get; set; }
        public virtual ICollection<QualityNCEmployee> QualityNCEmployees { get; set; }
        public virtual ICollection<QualityNCRole> QualityNCRoles { get; set; }
        public virtual ICollection<QualityNCTask> QualityNCTasks { get; set; }
        public virtual ICollection<QualityNCStockAdjustment> QualityNCStockAdjustments { get; set; }
        public virtual ICollection<RiskAudit> RiskAudits { get; set; }
    }
}
