//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iDAS.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class QualityCAPA
    {
        public QualityCAPA()
        {
            this.QualityCAPATasks = new HashSet<QualityCAPATask>();
        }
    
        public int ID { get; set; }
        public int QualityCAPARequirementID { get; set; }
        public bool IsEdit { get; set; }
        public bool IsApproval { get; set; }
        public bool IsAccept { get; set; }
        public bool IsComplete { get; set; }
        public bool IsPass { get; set; }
        public Nullable<System.DateTime> CompleteTime { get; set; }
        public Nullable<System.DateTime> CompleteRealTime { get; set; }
        public string Cause { get; set; }
        public string Solution { get; set; }
        public Nullable<int> ApprovalBy { get; set; }
        public Nullable<System.DateTime> ApprovalAt { get; set; }
        public string ApprovalNote { get; set; }
        public Nullable<System.DateTime> CreateAt { get; set; }
        public Nullable<int> CreateBy { get; set; }
        public Nullable<System.DateTime> UpdateAt { get; set; }
        public Nullable<int> UpdateBy { get; set; }
    
        public virtual QualityCAPARequirement QualityCAPARequirement { get; set; }
        public virtual ICollection<QualityCAPATask> QualityCAPATasks { get; set; }
    }
}
