//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iDAS.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class QualityMeetingResult
    {
        public QualityMeetingResult()
        {
            this.QualityMeetingResultAttachmentFiles = new HashSet<QualityMeetingResultAttachmentFile>();
        }
    
        public int ID { get; set; }
        public int QualityMeetingID { get; set; }
        public System.DateTime StartTime { get; set; }
        public System.DateTime EndTime { get; set; }
        public decimal Cost { get; set; }
        public string Content { get; set; }
        public string Address { get; set; }
        public string Note { get; set; }
        public Nullable<System.DateTime> CreateAt { get; set; }
        public Nullable<int> CreateBy { get; set; }
        public Nullable<System.DateTime> UpdateAt { get; set; }
        public Nullable<int> UpdateBy { get; set; }
    
        public virtual ICollection<QualityMeetingResultAttachmentFile> QualityMeetingResultAttachmentFiles { get; set; }
        public virtual QualityMeeting QualityMeeting { get; set; }
    }
}
