//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iDAS.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class QualityRisk
    {
        public QualityRisk()
        {
            this.QualityRiskContracts = new HashSet<QualityRiskContract>();
            this.QualityRiskControls = new HashSet<QualityRiskControl>();
            this.QualityRiskIncedents = new HashSet<QualityRiskIncedent>();
            this.QualityRiskLegals = new HashSet<QualityRiskLegal>();
            this.QualityRiskRegulatories = new HashSet<QualityRiskRegulatory>();
        }
    
        public int ID { get; set; }
        public int HumanDepartmentID { get; set; }
        public int RiskCategoryID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string Weakness { get; set; }
        public float LikeLiHood { get; set; }
        public float Impact { get; set; }
        public int Consequence { get; set; }
        public int HumanEmployeeID { get; set; }
        public bool IsFromRequire { get; set; }
        public bool IsFromAction { get; set; }
        public Nullable<int> CreateBy { get; set; }
        public Nullable<System.DateTime> CreateAt { get; set; }
        public Nullable<int> UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdateAt { get; set; }
    
        public virtual HumanDepartment HumanDepartment { get; set; }
        public virtual ICollection<QualityRiskContract> QualityRiskContracts { get; set; }
        public virtual ICollection<QualityRiskControl> QualityRiskControls { get; set; }
        public virtual ICollection<QualityRiskIncedent> QualityRiskIncedents { get; set; }
        public virtual ICollection<QualityRiskLegal> QualityRiskLegals { get; set; }
        public virtual ICollection<QualityRiskRegulatory> QualityRiskRegulatories { get; set; }
    }
}
