//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iDAS.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class QualityAuditResult
    {
        public int ID { get; set; }
        public int HumanDepartmentID { get; set; }
        public int QualityAuditProgramISOID { get; set; }
        public Nullable<int> QualityNCID { get; set; }
        public int ISOIndexCriteriaID { get; set; }
        public bool IsPass { get; set; }
        public Nullable<int> AuditBy { get; set; }
        public Nullable<System.DateTime> AuditAt { get; set; }
        public string AuditNote { get; set; }
        public Nullable<System.DateTime> CreateAt { get; set; }
        public Nullable<int> CreateBy { get; set; }
        public Nullable<System.DateTime> UpdateAt { get; set; }
        public Nullable<int> UpdateBy { get; set; }
    
        public virtual HumanDepartment HumanDepartment { get; set; }
        public virtual QualityAuditProgramISO QualityAuditProgramISO { get; set; }
        public virtual QualityNC QualityNC { get; set; }
    }
}
