//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iDAS.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class QualityRiskControl
    {
        public QualityRiskControl()
        {
            this.QualityRiskAudits = new HashSet<QualityRiskAudit>();
            this.QualityRiskControlTasks = new HashSet<QualityRiskControlTask>();
        }
    
        public int ID { get; set; }
        public int QualityRiskID { get; set; }
        public string Controls { get; set; }
        public int LikeLiHood { get; set; }
        public int QualityRiskTreatmentID { get; set; }
        public Nullable<System.DateTime> CompleteTime { get; set; }
        public bool IsEdit { get; set; }
        public bool IsApproval { get; set; }
        public bool IsAccept { get; set; }
        public Nullable<int> ApprovalBy { get; set; }
        public Nullable<System.DateTime> ApprovalAt { get; set; }
        public string Note { get; set; }
        public Nullable<int> CreateBy { get; set; }
        public Nullable<System.DateTime> CreateAt { get; set; }
        public Nullable<int> UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdateAt { get; set; }
    
        public virtual ICollection<QualityRiskAudit> QualityRiskAudits { get; set; }
        public virtual QualityRisk QualityRisk { get; set; }
        public virtual ICollection<QualityRiskControlTask> QualityRiskControlTasks { get; set; }
    }
}
