//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iDAS.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class QualityAuditPlan
    {
        public QualityAuditPlan()
        {
            this.QualityAuditPrograms = new HashSet<QualityAuditProgram>();
        }
    
        public int ID { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public int ISOID { get; set; }
        public System.DateTime StartTime { get; set; }
        public System.DateTime EndTime { get; set; }
        public bool IsNew { get; set; }
        public bool IsEdit { get; set; }
        public bool IsApproval { get; set; }
        public bool IsAccept { get; set; }
        public int ApporvalBy { get; set; }
        public Nullable<System.DateTime> ApprovalAt { get; set; }
        public string Scope { get; set; }
        public string Requirement { get; set; }
        public string Note { get; set; }
        public bool IsPass { get; set; }
        public string AuditNote { get; set; }
        public Nullable<System.DateTime> CreateAt { get; set; }
        public Nullable<int> CreateBy { get; set; }
        public Nullable<System.DateTime> UpdateAt { get; set; }
        public Nullable<int> UpdateBy { get; set; }
    
        public virtual ICollection<QualityAuditProgram> QualityAuditPrograms { get; set; }
    }
}
