//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iDAS.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReportTemplate
    {
        public ReportTemplate()
        {
            this.Reports = new HashSet<Report>();
        }
    
        public int ID { get; set; }
        public string ModuleCode { get; set; }
        public string FunctionCode { get; set; }
        public string Name { get; set; }
        public string File { get; set; }
        public string PathUpload { get; set; }
        public string PathReport { get; set; }
        public string Type { get; set; }
        public Nullable<double> Size { get; set; }
        public bool IsMap { get; set; }
        public bool IsActive { get; set; }
        public bool IsDelete { get; set; }
        public Nullable<System.DateTime> CreateAt { get; set; }
        public Nullable<int> CreateBy { get; set; }
        public Nullable<System.DateTime> UpdateAt { get; set; }
        public Nullable<int> UpdateBy { get; set; }
    
        public virtual ICollection<Report> Reports { get; set; }
    }
}
