//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iDAS.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class RiskControl
    {
        public RiskControl()
        {
            this.RiskAudits = new HashSet<RiskAudit>();
            this.RiskControlSolutions = new HashSet<RiskControlSolution>();
            this.RiskControlTasks = new HashSet<RiskControlTask>();
        }
    
        public int ID { get; set; }
        public int RiskID { get; set; }
        public string Controls { get; set; }
        public float LikeLiHood { get; set; }
        public int RiskTreatmentID { get; set; }
        public Nullable<System.DateTime> CompleteTime { get; set; }
        public bool IsEdit { get; set; }
        public bool IsApproval { get; set; }
        public bool IsAccept { get; set; }
        public Nullable<int> ApprovalBy { get; set; }
        public Nullable<System.DateTime> ApprovalAt { get; set; }
        public string Note { get; set; }
        public Nullable<int> CreateBy { get; set; }
        public Nullable<System.DateTime> CreateAt { get; set; }
        public Nullable<int> UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdateAt { get; set; }
        public float NowLikeLiHood { get; set; }
        public float NowImpact { get; set; }
        public float NowConsequence { get; set; }
    
        public virtual ICollection<RiskAudit> RiskAudits { get; set; }
        public virtual Risk Risk { get; set; }
        public virtual ICollection<RiskControlSolution> RiskControlSolutions { get; set; }
        public virtual ICollection<RiskControlTask> RiskControlTasks { get; set; }
    }
}
