//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iDAS.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class Risk
    {
        public Risk()
        {
            this.RiskContracts = new HashSet<RiskContract>();
            this.RiskControls = new HashSet<RiskControl>();
            this.RiskIncedents = new HashSet<RiskIncedent>();
            this.RiskLegals = new HashSet<RiskLegal>();
            this.RiskRegulatories = new HashSet<RiskRegulatory>();
        }
    
        public int ID { get; set; }
        public int HumanDepartmentID { get; set; }
        public int RiskCategoryID { get; set; }
        public string Name { get; set; }
        public string Weakness { get; set; }
        public string Action { get; set; }
        public int HumanEmployeeID { get; set; }
        public bool IsFromRequire { get; set; }
        public bool IsFromAction { get; set; }
        public bool IsFromLegal { get; set; }
        public bool IsFromRegulatory { get; set; }
        public bool IsSend { get; set; }
        public float LikeLiHood { get; set; }
        public float Impact { get; set; }
        public float Consequence { get; set; }
        public Nullable<int> CreateBy { get; set; }
        public Nullable<System.DateTime> CreateAt { get; set; }
        public Nullable<int> UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdateAt { get; set; }
    
        public virtual HumanDepartment HumanDepartment { get; set; }
        public virtual ICollection<RiskContract> RiskContracts { get; set; }
        public virtual ICollection<RiskControl> RiskControls { get; set; }
        public virtual ICollection<RiskIncedent> RiskIncedents { get; set; }
        public virtual ICollection<RiskLegal> RiskLegals { get; set; }
        public virtual ICollection<RiskRegulatory> RiskRegulatories { get; set; }
    }
}
