//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iDAS.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceCommandContract
    {
        public ServiceCommandContract()
        {
            this.ServicePlans = new HashSet<ServicePlan>();
        }
    
        public int ID { get; set; }
        public int ServiceCommandID { get; set; }
        public Nullable<int> CustomerContractID { get; set; }
        public Nullable<System.DateTime> CreateAt { get; set; }
        public Nullable<int> CreateBy { get; set; }
        public Nullable<System.DateTime> UpdateAt { get; set; }
        public Nullable<int> UpdateBy { get; set; }
    
        public virtual CustomerContract CustomerContract { get; set; }
        public virtual ServiceCommand ServiceCommand { get; set; }
        public virtual ICollection<ServicePlan> ServicePlans { get; set; }
    }
}
