//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iDAS.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceStage
    {
        public ServiceStage()
        {
            this.ServicePlanStages = new HashSet<ServicePlanStage>();
        }
    
        public int ID { get; set; }
        public int ServiceID { get; set; }
        public string Name { get; set; }
        public Nullable<float> Time { get; set; }
        public Nullable<int> TimeUnit { get; set; }
        public Nullable<int> Order { get; set; }
        public bool IsUse { get; set; }
        public string Note { get; set; }
        public Nullable<System.DateTime> CreateAt { get; set; }
        public Nullable<int> CreateBy { get; set; }
        public Nullable<System.DateTime> UpdateAt { get; set; }
        public Nullable<int> UpdateBy { get; set; }
    
        public virtual ICollection<ServicePlanStage> ServicePlanStages { get; set; }
        public virtual Service Service { get; set; }
    }
}
