//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iDAS.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class Service
    {
        public Service()
        {
            this.CustomerOrders = new HashSet<CustomerOrder>();
            this.ServiceStages = new HashSet<ServiceStage>();
        }
    
        public int ID { get; set; }
        public int ServiceCategoryID { get; set; }
        public string Name { get; set; }
        public string Code { get; set; }
        public bool IsUse { get; set; }
        public bool IsDelete { get; set; }
        public Nullable<decimal> Cost { get; set; }
        public string Note { get; set; }
        public Nullable<System.DateTime> CreateAt { get; set; }
        public Nullable<int> CreateBy { get; set; }
        public Nullable<System.DateTime> UpdateAt { get; set; }
        public Nullable<int> UpdateBy { get; set; }
    
        public virtual ICollection<CustomerOrder> CustomerOrders { get; set; }
        public virtual ServiceCategory ServiceCategory { get; set; }
        public virtual ICollection<ServiceStage> ServiceStages { get; set; }
    }
}
