//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iDAS.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockInventory
    {
        public StockInventory()
        {
            this.StockInventoryDetails = new HashSet<StockInventoryDetail>();
        }
    
        public int ID { get; set; }
        public string RefID { get; set; }
        public Nullable<System.DateTime> RefDate { get; set; }
        public Nullable<int> RefType { get; set; }
        public Nullable<int> Stock_ID { get; set; }
        public Nullable<int> StockProductID { get; set; }
        public Nullable<int> Customer_ID { get; set; }
        public Nullable<int> Currency_ID { get; set; }
        public Nullable<System.DateTime> Limit { get; set; }
        public Nullable<decimal> Quantity { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string Batch { get; set; }
        public string Serial { get; set; }
        public string ChassyNo { get; set; }
        public string Color { get; set; }
        public string Location { get; set; }
        public Nullable<decimal> Width { get; set; }
        public Nullable<decimal> Height { get; set; }
        public string Orgin { get; set; }
        public string Size { get; set; }
        public string Description { get; set; }
        public System.DateTime CreateAt { get; set; }
        public int CreateBy { get; set; }
        public Nullable<System.DateTime> UpdateAt { get; set; }
        public Nullable<int> UpdateBy { get; set; }
    
        public virtual StockProduct StockProduct { get; set; }
        public virtual ICollection<StockInventoryDetail> StockInventoryDetails { get; set; }
    }
}
