//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iDAS.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockProductPrice
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> RefDate { get; set; }
        public Nullable<short> RefStatus { get; set; }
        public Nullable<System.DateTime> BeginDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<int> Product_ID { get; set; }
        public Nullable<int> Customer_ID { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<decimal> DiscountRate { get; set; }
        public Nullable<decimal> CommissionRate { get; set; }
        public Nullable<decimal> Quantity { get; set; }
        public Nullable<decimal> BeginAmount { get; set; }
        public Nullable<decimal> EndAmount { get; set; }
        public bool IsPublic { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string OwnerID { get; set; }
        public string Description { get; set; }
        public Nullable<long> Sorted { get; set; }
        public bool Active { get; set; }
        public Nullable<int> UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdateAt { get; set; }
    }
}
