//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iDAS.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockAdjustment
    {
        public StockAdjustment()
        {
            this.QualityNCStockAdjustments = new HashSet<QualityNCStockAdjustment>();
            this.StockAdjustmentDetails = new HashSet<StockAdjustmentDetail>();
        }
    
        public int ID { get; set; }
        public System.DateTime RefDate { get; set; }
        public string Ref_OrgNo { get; set; }
        public Nullable<int> RefType { get; set; }
        public Nullable<int> Employee_ID { get; set; }
        public Nullable<int> StockID { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public bool Accept { get; set; }
        public bool IsClose { get; set; }
        public string Description { get; set; }
        public bool Active { get; set; }
        public System.DateTime CreateAt { get; set; }
        public int CreateBy { get; set; }
        public Nullable<System.DateTime> UpdateAt { get; set; }
        public Nullable<int> UpdateBy { get; set; }
    
        public virtual ICollection<QualityNCStockAdjustment> QualityNCStockAdjustments { get; set; }
        public virtual ICollection<StockAdjustmentDetail> StockAdjustmentDetails { get; set; }
    }
}
