//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iDAS.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockProduct
    {
        public StockProduct()
        {
            this.ProductDevelopmentRequirements = new HashSet<ProductDevelopmentRequirement>();
            this.ProductionPerformMaterias = new HashSet<ProductionPerformMateria>();
            this.ProductionPerformProductErrors = new HashSet<ProductionPerformProductError>();
            this.ProductionPlanMaterials = new HashSet<ProductionPlanMaterial>();
            this.ProductionPlanProducts = new HashSet<ProductionPlanProduct>();
            this.ProductionRequirements = new HashSet<ProductionRequirement>();
            this.ProductionStageMaterials = new HashSet<ProductionStageMaterial>();
            this.ProductionStageProducts = new HashSet<ProductionStageProduct>();
            this.ProductionStages = new HashSet<ProductionStage>();
            this.StockAdjustmentDetails = new HashSet<StockAdjustmentDetail>();
            this.StockInventories = new HashSet<StockInventory>();
            this.StockInventoryDetails = new HashSet<StockInventoryDetail>();
            this.StockInwardDetails = new HashSet<StockInwardDetail>();
            this.StockOutwardDetails = new HashSet<StockOutwardDetail>();
            this.StockProductBuilds = new HashSet<StockProductBuild>();
            this.StockTransferDetails = new HashSet<StockTransferDetail>();
            this.SuppliersOrderDetails = new HashSet<SuppliersOrderDetail>();
            this.SuppliersOrderRequirementDetails = new HashSet<SuppliersOrderRequirementDetail>();
        }
    
        public int ID { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public string NameEN { get; set; }
        public Nullable<int> Type_ID { get; set; }
        public Nullable<int> Manufacturer_ID { get; set; }
        public Nullable<int> Model_ID { get; set; }
        public Nullable<int> StockProductGroupID { get; set; }
        public Nullable<int> Provider_ID { get; set; }
        public string Origin { get; set; }
        public string Barcode { get; set; }
        public Nullable<int> Unit_ID { get; set; }
        public string UnitConvert { get; set; }
        public Nullable<decimal> UnitRate { get; set; }
        public Nullable<decimal> Org_Price { get; set; }
        public Nullable<decimal> Sale_Price { get; set; }
        public Nullable<decimal> Retail_Price { get; set; }
        public Nullable<decimal> Quantity { get; set; }
        public Nullable<decimal> CurrentCost { get; set; }
        public Nullable<decimal> AverageCost { get; set; }
        public Nullable<int> Warranty { get; set; }
        public Nullable<decimal> VAT_ID { get; set; }
        public Nullable<decimal> ImportTax_ID { get; set; }
        public Nullable<decimal> ExportTax_ID { get; set; }
        public Nullable<decimal> LuxuryTax_ID { get; set; }
        public string Customer_ID { get; set; }
        public string Customer_Name { get; set; }
        public Nullable<short> CostMethod { get; set; }
        public Nullable<decimal> MinStock { get; set; }
        public Nullable<decimal> MaxStock { get; set; }
        public Nullable<decimal> Discount { get; set; }
        public Nullable<decimal> Commission { get; set; }
        public string Description { get; set; }
        public string Color { get; set; }
        public bool Expiry { get; set; }
        public Nullable<decimal> LimitOrders { get; set; }
        public Nullable<decimal> ExpiryValue { get; set; }
        public bool Batch { get; set; }
        public Nullable<decimal> Depth { get; set; }
        public Nullable<decimal> Height { get; set; }
        public Nullable<decimal> Width { get; set; }
        public Nullable<decimal> Thickness { get; set; }
        public string Size { get; set; }
        public byte[] ImageProduct { get; set; }
        public Nullable<int> Currency_ID { get; set; }
        public Nullable<decimal> ExchangeRate { get; set; }
        public Nullable<int> StockID { get; set; }
        public bool Serial { get; set; }
        public bool Active { get; set; }
        public System.DateTime CreateAt { get; set; }
        public int CreateBy { get; set; }
        public Nullable<System.DateTime> UpdateAt { get; set; }
        public Nullable<int> UpdateBy { get; set; }
    
        public virtual ICollection<ProductDevelopmentRequirement> ProductDevelopmentRequirements { get; set; }
        public virtual ICollection<ProductionPerformMateria> ProductionPerformMaterias { get; set; }
        public virtual ICollection<ProductionPerformProductError> ProductionPerformProductErrors { get; set; }
        public virtual ICollection<ProductionPlanMaterial> ProductionPlanMaterials { get; set; }
        public virtual ICollection<ProductionPlanProduct> ProductionPlanProducts { get; set; }
        public virtual ICollection<ProductionRequirement> ProductionRequirements { get; set; }
        public virtual ICollection<ProductionStageMaterial> ProductionStageMaterials { get; set; }
        public virtual ICollection<ProductionStageProduct> ProductionStageProducts { get; set; }
        public virtual ICollection<ProductionStage> ProductionStages { get; set; }
        public virtual ICollection<StockAdjustmentDetail> StockAdjustmentDetails { get; set; }
        public virtual ICollection<StockInventory> StockInventories { get; set; }
        public virtual ICollection<StockInventoryDetail> StockInventoryDetails { get; set; }
        public virtual ICollection<StockInwardDetail> StockInwardDetails { get; set; }
        public virtual ICollection<StockOutwardDetail> StockOutwardDetails { get; set; }
        public virtual ICollection<StockProductBuild> StockProductBuilds { get; set; }
        public virtual StockProductGroup StockProductGroup { get; set; }
        public virtual Stock Stock { get; set; }
        public virtual ICollection<StockTransferDetail> StockTransferDetails { get; set; }
        public virtual ICollection<SuppliersOrderDetail> SuppliersOrderDetails { get; set; }
        public virtual ICollection<SuppliersOrderRequirementDetail> SuppliersOrderRequirementDetails { get; set; }
    }
}
