//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iDAS.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockAdjustmentDetail
    {
        public int ID { get; set; }
        public int StockAdjustmentID { get; set; }
        public int StockProductID { get; set; }
        public string Product_Name { get; set; }
        public Nullable<int> Stock_ID { get; set; }
        public Nullable<int> Unit_ID { get; set; }
        public Nullable<decimal> UnitConvert { get; set; }
        public Nullable<decimal> Width { get; set; }
        public Nullable<decimal> Height { get; set; }
        public string Orgin { get; set; }
        public Nullable<decimal> CurrentQty { get; set; }
        public Nullable<decimal> NewQty { get; set; }
        public Nullable<decimal> QtyDiff { get; set; }
        public Nullable<decimal> UnitPrice { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<decimal> QtyConvert { get; set; }
        public Nullable<long> StoreID { get; set; }
        public string Batch { get; set; }
        public string Serial { get; set; }
        public string Description { get; set; }
        public Nullable<long> Sorted { get; set; }
        public System.DateTime CreateAt { get; set; }
        public int CreateBy { get; set; }
        public Nullable<System.DateTime> UpdateAt { get; set; }
        public Nullable<int> UpdateBy { get; set; }
    
        public virtual StockAdjustment StockAdjustment { get; set; }
        public virtual StockProduct StockProduct { get; set; }
    }
}
