//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iDAS.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class SupplierAuditResult
    {
        public int ID { get; set; }
        public int SupplierAuditID { get; set; }
        public int QualityCriteria { get; set; }
        public Nullable<decimal> Point { get; set; }
        public Nullable<decimal> Factory { get; set; }
        public Nullable<decimal> TotalPoint { get; set; }
        public Nullable<System.DateTime> CreateAt { get; set; }
        public int CreateBy { get; set; }
        public System.DateTime UpdateAt { get; set; }
        public Nullable<int> UpdateBy { get; set; }
    
        public virtual QualityCriteria QualityCriteria1 { get; set; }
        public virtual SupplierAudit SupplierAudit { get; set; }
    }
}
