//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iDAS.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class SupplierAudit
    {
        public SupplierAudit()
        {
            this.SupplierAuditResults = new HashSet<SupplierAuditResult>();
        }
    
        public int ID { get; set; }
        public int SupplierID { get; set; }
        public int SupplierAuditPlanID { get; set; }
        public Nullable<System.DateTime> CreateAt { get; set; }
        public Nullable<int> CreateBy { get; set; }
        public Nullable<System.DateTime> UpdateAt { get; set; }
        public Nullable<int> UpdateBy { get; set; }
        public Nullable<bool> IsPass { get; set; }
    
        public virtual SupplierAuditPlan SupplierAuditPlan { get; set; }
        public virtual ICollection<SupplierAuditResult> SupplierAuditResults { get; set; }
        public virtual Supplier Supplier { get; set; }
    }
}
