//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iDAS.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class SuppliersOrder
    {
        public SuppliersOrder()
        {
            this.SuppliersBidOrders = new HashSet<SuppliersBidOrder>();
            this.SuppliersBills = new HashSet<SuppliersBill>();
            this.SuppliersOrderDetails = new HashSet<SuppliersOrderDetail>();
        }
    
        public int ID { get; set; }
        public string CODE { get; set; }
        public Nullable<int> SupplierID { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
        public Nullable<System.DateTime> ShipDate { get; set; }
        public Nullable<System.DateTime> ReciepDate { get; set; }
        public Nullable<byte> Payment { get; set; }
        public string ReciepPlace { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<System.DateTime> CreateAt { get; set; }
        public Nullable<int> CreateBy { get; set; }
        public Nullable<System.DateTime> UpdateAt { get; set; }
        public Nullable<int> UpdateBy { get; set; }
        public string Name { get; set; }
        public string Note { get; set; }
        public Nullable<bool> IsApproval { get; set; }
        public Nullable<System.DateTime> ApprovalAt { get; set; }
        public Nullable<int> ApprovalBy { get; set; }
        public string ApprovalNote { get; set; }
        public Nullable<bool> IsEdit { get; set; }
        public Nullable<bool> IsAccept { get; set; }
        public Nullable<int> Discount { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string ShipType { get; set; }
    
        public virtual Supplier Supplier { get; set; }
        public virtual ICollection<SuppliersBidOrder> SuppliersBidOrders { get; set; }
        public virtual ICollection<SuppliersBill> SuppliersBills { get; set; }
        public virtual ICollection<SuppliersOrderDetail> SuppliersOrderDetails { get; set; }
    }
}
