//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iDAS.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class SuppliersBill
    {
        public int ID { get; set; }
        public int SuppliersOrderID { get; set; }
        public Nullable<decimal> PayedMoney { get; set; }
        public Nullable<System.DateTime> PayDate { get; set; }
        public Nullable<byte> BillType { get; set; }
        public Nullable<System.DateTime> CreateAt { get; set; }
        public Nullable<int> CreateBy { get; set; }
        public Nullable<System.DateTime> UpdateAt { get; set; }
        public Nullable<int> UpdateBy { get; set; }
        public string Note { get; set; }
    
        public virtual SuppliersOrder SuppliersOrder { get; set; }
    }
}
