//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iDAS.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class SuppliersOrderDetail
    {
        public int ID { get; set; }
        public Nullable<int> SuppliersOrderID { get; set; }
        public Nullable<int> StocksProductID { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<System.DateTime> CreateAt { get; set; }
        public Nullable<int> CreateBy { get; set; }
        public Nullable<System.DateTime> UpdateAt { get; set; }
        public Nullable<int> UpdateBy { get; set; }
        public Nullable<decimal> Price { get; set; }
        public string Note { get; set; }
        public Nullable<int> ReciveQuantity { get; set; }
        public Nullable<int> ReciveQuality { get; set; }
        public Nullable<int> SuppliersOrderRequirementDetailID { get; set; }
    
        public virtual StockProduct StockProduct { get; set; }
        public virtual SuppliersOrder SuppliersOrder { get; set; }
    }
}
