//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iDAS.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class Supplier
    {
        public Supplier()
        {
            this.SupplierAudits = new HashSet<SupplierAudit>();
            this.SuppliersBidOrders = new HashSet<SuppliersBidOrder>();
            this.SuppliersOrders = new HashSet<SuppliersOrder>();
        }
    
        public int ID { get; set; }
        public int SuppliersGroupID { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public string BrandName { get; set; }
        public string Email { get; set; }
        public string Website { get; set; }
        public string Phone { get; set; }
        public string Fax { get; set; }
        public string Tax { get; set; }
        public string AcountNumber { get; set; }
        public string BankName { get; set; }
        public string Address { get; set; }
        public Nullable<int> CountryId { get; set; }
        public Nullable<int> ProvinceId { get; set; }
        public string Representative { get; set; }
        public Nullable<double> TotalImportValue { get; set; }
        public Nullable<double> IsOwedOn { get; set; }
        public string Position { get; set; }
        public bool IsCustomer { get; set; }
        public Nullable<System.Guid> AttachmentFileID { get; set; }
        public string Description { get; set; }
        public Nullable<int> Status { get; set; }
        public System.DateTime CreateAt { get; set; }
        public int CreateBy { get; set; }
        public Nullable<System.DateTime> UpdateAt { get; set; }
        public Nullable<int> UpdateBy { get; set; }
        public string Commodity { get; set; }
    
        public virtual AttachmentFile AttachmentFile { get; set; }
        public virtual ICollection<SupplierAudit> SupplierAudits { get; set; }
        public virtual SuppliersGroup SuppliersGroup { get; set; }
        public virtual ICollection<SuppliersBidOrder> SuppliersBidOrders { get; set; }
        public virtual ICollection<SuppliersOrder> SuppliersOrders { get; set; }
    }
}
