//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iDAS.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class SuppliersOrderRequirement
    {
        public SuppliersOrderRequirement()
        {
            this.SuppliersOrderRequirementDetails = new HashSet<SuppliersOrderRequirementDetail>();
        }
    
        public int ID { get; set; }
        public string CODE { get; set; }
        public string Name { get; set; }
        public string Note { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<System.DateTime> CreateAt { get; set; }
        public Nullable<int> CreateBy { get; set; }
        public Nullable<System.DateTime> UpdateAt { get; set; }
        public Nullable<int> UpdateBy { get; set; }
        public Nullable<bool> IsApproval { get; set; }
        public Nullable<System.DateTime> ApprovalAt { get; set; }
        public Nullable<int> ApprovalBy { get; set; }
        public string ApprovalNote { get; set; }
        public Nullable<bool> IsEdit { get; set; }
        public Nullable<bool> IsAccept { get; set; }
    
        public virtual ICollection<SuppliersOrderRequirementDetail> SuppliersOrderRequirementDetails { get; set; }
    }
}
