//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iDAS.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class SuppliersBidOrder
    {
        public SuppliersBidOrder()
        {
            this.SupplierBidToAttachmentFiles = new HashSet<SupplierBidToAttachmentFile>();
        }
    
        public int ID { get; set; }
        public int SuppliersOrderID { get; set; }
        public int SupplierID { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<System.DateTime> ReceiveDate { get; set; }
        public Nullable<System.DateTime> CreateAt { get; set; }
        public Nullable<int> CreateBy { get; set; }
        public Nullable<System.DateTime> UpdateAt { get; set; }
        public Nullable<int> UpdateBy { get; set; }
        public Nullable<bool> Status { get; set; }
        public string Contents { get; set; }
    
        public virtual ICollection<SupplierBidToAttachmentFile> SupplierBidToAttachmentFiles { get; set; }
        public virtual Supplier Supplier { get; set; }
        public virtual SuppliersOrder SuppliersOrder { get; set; }
    }
}
