//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iDAS.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaskRequest
    {
        public int ID { get; set; }
        public Nullable<int> ParentID { get; set; }
        public int HumanDepartmentID { get; set; }
        public int HumanEmployeeID { get; set; }
        public int TaskCategoryID { get; set; }
        public int TaskLevelID { get; set; }
        public string Name { get; set; }
        public System.DateTime StartTime { get; set; }
        public System.DateTime EndTime { get; set; }
        public decimal Cost { get; set; }
        public string Contents { get; set; }
        public string Reason { get; set; }
        public string Note { get; set; }
        public bool IsEdit { get; set; }
        public bool IsNew { get; set; }
        public bool IsApproval { get; set; }
        public bool IsAccept { get; set; }
        public bool IsDelete { get; set; }
        public Nullable<int> ApprovalBy { get; set; }
        public Nullable<System.DateTime> ApprovalAt { get; set; }
        public Nullable<System.DateTime> CreateAt { get; set; }
        public Nullable<int> CreateBy { get; set; }
        public Nullable<System.DateTime> UpdateAt { get; set; }
        public Nullable<int> UpdateBy { get; set; }
    
        public virtual HumanDepartment HumanDepartment { get; set; }
        public virtual HumanEmployee HumanEmployee { get; set; }
        public virtual TaskLevel TaskLevel { get; set; }
    }
}
