//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iDAS.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaskPersonal
    {
        public int ID { get; set; }
        public int TaskID { get; set; }
        public int PerformBy { get; set; }
        public bool IsNew { get; set; }
        public bool IsCreate { get; set; }
        public bool IsPerform { get; set; }
        public bool IsClosed { get; set; }
        public Nullable<System.DateTime> CreateAt { get; set; }
        public Nullable<int> CreateBy { get; set; }
        public Nullable<System.DateTime> UpdateAt { get; set; }
        public Nullable<int> UpdateBy { get; set; }
    
        public virtual Task Task { get; set; }
    }
}
