//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iDAS.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class Task
    {
        public Task()
        {
            this.DispatchGoTasks = new HashSet<DispatchGoTask>();
            this.DispatchToTasks = new HashSet<DispatchToTask>();
            this.DocumentTasks = new HashSet<DocumentTask>();
            this.HumanRecruitmentTasks = new HashSet<HumanRecruitmentTask>();
            this.QualityCAPATasks = new HashSet<QualityCAPATask>();
            this.QualityMeetingTasks = new HashSet<QualityMeetingTask>();
            this.QualityNCTasks = new HashSet<QualityNCTask>();
            this.QualityPlanTasks = new HashSet<QualityPlanTask>();
            this.RiskControlTasks = new HashSet<RiskControlTask>();
            this.TaskAttachmentFiles = new HashSet<TaskAttachmentFile>();
            this.TaskCCs = new HashSet<TaskCC>();
            this.TaskChecks = new HashSet<TaskCheck>();
            this.TaskComments = new HashSet<TaskComment>();
            this.TaskHistories = new HashSet<TaskHistory>();
            this.TaskPerforms = new HashSet<TaskPerform>();
            this.TaskPersonals = new HashSet<TaskPersonal>();
        }
    
        public int ID { get; set; }
        public int ParentID { get; set; }
        public int HumanDepartmentID { get; set; }
        public int HumanEmployeeID { get; set; }
        public int TaskCategoryID { get; set; }
        public int TaskLevelID { get; set; }
        public Nullable<int> AuditID { get; set; }
        public string Name { get; set; }
        public System.DateTime StartTime { get; set; }
        public System.DateTime EndTime { get; set; }
        public bool IsPrivate { get; set; }
        public bool IsNew { get; set; }
        public bool IsEdit { get; set; }
        public bool IsComplete { get; set; }
        public bool IsPass { get; set; }
        public bool IsPause { get; set; }
        public decimal Rate { get; set; }
        public decimal Cost { get; set; }
        public Nullable<System.DateTime> CompleteTime { get; set; }
        public string Content { get; set; }
        public string Note { get; set; }
        public Nullable<System.DateTime> CreateAt { get; set; }
        public Nullable<int> CreateBy { get; set; }
        public Nullable<System.DateTime> UpdateAt { get; set; }
        public Nullable<int> UpdateBy { get; set; }
    
        public virtual Audit Audit { get; set; }
        public virtual ICollection<DispatchGoTask> DispatchGoTasks { get; set; }
        public virtual ICollection<DispatchToTask> DispatchToTasks { get; set; }
        public virtual ICollection<DocumentTask> DocumentTasks { get; set; }
        public virtual HumanDepartment HumanDepartment { get; set; }
        public virtual HumanEmployee HumanEmployee { get; set; }
        public virtual ICollection<HumanRecruitmentTask> HumanRecruitmentTasks { get; set; }
        public virtual ICollection<QualityCAPATask> QualityCAPATasks { get; set; }
        public virtual ICollection<QualityMeetingTask> QualityMeetingTasks { get; set; }
        public virtual ICollection<QualityNCTask> QualityNCTasks { get; set; }
        public virtual ICollection<QualityPlanTask> QualityPlanTasks { get; set; }
        public virtual ICollection<RiskControlTask> RiskControlTasks { get; set; }
        public virtual ICollection<TaskAttachmentFile> TaskAttachmentFiles { get; set; }
        public virtual TaskCategory TaskCategory { get; set; }
        public virtual ICollection<TaskCC> TaskCCs { get; set; }
        public virtual ICollection<TaskCheck> TaskChecks { get; set; }
        public virtual ICollection<TaskComment> TaskComments { get; set; }
        public virtual ICollection<TaskHistory> TaskHistories { get; set; }
        public virtual TaskLevel TaskLevel { get; set; }
        public virtual ICollection<TaskPerform> TaskPerforms { get; set; }
        public virtual ICollection<TaskPersonal> TaskPersonals { get; set; }
    }
}
