//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iDAS.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaskHistory
    {
        public int ID { get; set; }
        public int TaskID { get; set; }
        public int ParentID { get; set; }
        public int DepartmentID { get; set; }
        public int EmployeeID { get; set; }
        public int CategoryID { get; set; }
        public int LevelID { get; set; }
        public string Name { get; set; }
        public System.DateTime StartTime { get; set; }
        public System.DateTime EndTime { get; set; }
        public bool IsPrivate { get; set; }
        public bool IsNew { get; set; }
        public bool IsEdit { get; set; }
        public bool IsComplete { get; set; }
        public bool IsPass { get; set; }
        public bool IsPause { get; set; }
        public decimal Rate { get; set; }
        public decimal Cost { get; set; }
        public Nullable<System.DateTime> CompleteTime { get; set; }
        public string Content { get; set; }
        public string Note { get; set; }
        public string Reason { get; set; }
        public bool IsChange { get; set; }
        public string ChangeNote { get; set; }
        public Nullable<System.DateTime> CreateAt { get; set; }
        public Nullable<int> CreateBy { get; set; }
        public Nullable<System.DateTime> UpdateAt { get; set; }
        public Nullable<int> UpdateBy { get; set; }
    
        public virtual Task Task { get; set; }
    }
}
