//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iDAS.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public Customer()
        {
            this.CustomerRegisterDataSizes = new HashSet<CustomerRegisterDataSize>();
            this.CustomerRegisterProducts = new HashSet<CustomerRegisterProduct>();
            this.CustomerRegisterServices = new HashSet<CustomerRegisterService>();
            this.CustomerSystems = new HashSet<CustomerSystem>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public string Password { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public string Address { get; set; }
        public Nullable<System.DateTime> Birthday { get; set; }
        public string Role { get; set; }
        public string Represent { get; set; }
        public string Scope { get; set; }
        public string CompanySize { get; set; }
        public string TaxCode { get; set; }
        public string Website { get; set; }
        public Nullable<System.Guid> FileID { get; set; }
        public Nullable<int> WebCustomerCityID { get; set; }
        public bool IsPersonal { get; set; }
        public bool IsActive { get; set; }
        public bool IsDelete { get; set; }
        public Nullable<System.DateTime> RegisterAt { get; set; }
        public Nullable<System.DateTime> RefreshAt { get; set; }
        public Nullable<System.DateTime> CreateAt { get; set; }
        public Nullable<int> CreateBy { get; set; }
        public Nullable<System.DateTime> UpdateAt { get; set; }
        public Nullable<int> UpdateBy { get; set; }
    
        public virtual ICollection<CustomerRegisterDataSize> CustomerRegisterDataSizes { get; set; }
        public virtual ICollection<CustomerRegisterProduct> CustomerRegisterProducts { get; set; }
        public virtual ICollection<CustomerRegisterService> CustomerRegisterServices { get; set; }
        public virtual File File { get; set; }
        public virtual WebCustomerCity WebCustomerCity { get; set; }
        public virtual ICollection<CustomerSystem> CustomerSystems { get; set; }
    }
}
