//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iDAS.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerRegisterProduct
    {
        public int ID { get; set; }
        public int CustomerID { get; set; }
        public int WebProductID { get; set; }
        public int WebProductMethodID { get; set; }
        public int WebProductScopeID { get; set; }
        public int WebProductDateSizeID { get; set; }
        public bool IsNew { get; set; }
        public bool IsContact { get; set; }
        public bool IsAccept { get; set; }
        public bool IsActive { get; set; }
        public bool IsDelete { get; set; }
        public string Note { get; set; }
        public Nullable<System.DateTime> RegisterAt { get; set; }
        public Nullable<System.DateTime> ContactAt { get; set; }
        public Nullable<System.DateTime> CompleteAt { get; set; }
        public Nullable<int> CreateBy { get; set; }
        public Nullable<System.DateTime> CreateAt { get; set; }
        public Nullable<int> UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdateAt { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual WebProductDataSize WebProductDataSize { get; set; }
        public virtual WebProductMethod WebProductMethod { get; set; }
        public virtual WebProductScope WebProductScope { get; set; }
        public virtual WebProduct WebProduct { get; set; }
    }
}
