//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iDAS.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerSystem
    {
        public CustomerSystem()
        {
            this.CustomerSystemMails = new HashSet<CustomerSystemMail>();
            this.CustomerSystemModules = new HashSet<CustomerSystemModule>();
        }
    
        public int ID { get; set; }
        public int CustomerID { get; set; }
        public int CenterSystemID { get; set; }
        public string Code { get; set; }
        public string Company { get; set; }
        public Nullable<System.Guid> FileID { get; set; }
        public Nullable<int> DataSize { get; set; }
        public bool IsNew { get; set; }
        public bool IsUpgradeData { get; set; }
        public bool IsUpgradeModule { get; set; }
        public bool IsActive { get; set; }
        public bool IsDelete { get; set; }
        public string DBName { get; set; }
        public string DBSource { get; set; }
        public string DBUserID { get; set; }
        public string DBPassword { get; set; }
        public Nullable<System.DateTime> CompleteAt { get; set; }
        public Nullable<System.DateTime> CreateAt { get; set; }
        public Nullable<int> CreateBy { get; set; }
        public Nullable<System.DateTime> UpdateAt { get; set; }
        public Nullable<int> UpdateBy { get; set; }
    
        public virtual CenterSystem CenterSystem { get; set; }
        public virtual Customer Customer { get; set; }
        public virtual ICollection<CustomerSystemMail> CustomerSystemMails { get; set; }
        public virtual ICollection<CustomerSystemModule> CustomerSystemModules { get; set; }
        public virtual File File { get; set; }
    }
}
