//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iDAS.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerSystemMail
    {
        public int ID { get; set; }
        public int CustomerSystemID { get; set; }
        public bool EnableSSL { get; set; }
        public string SmtpHost { get; set; }
        public int SmtpPort { get; set; }
        public string PopHost { get; set; }
        public int PopPort { get; set; }
        public bool IsBodyHtml { get; set; }
        public string UserName { get; set; }
        public string UserPassword { get; set; }
        public bool IsActived { get; set; }
        public Nullable<System.DateTime> CreateAt { get; set; }
        public Nullable<int> CreateBy { get; set; }
        public Nullable<System.DateTime> UpdateAt { get; set; }
        public Nullable<int> UpdateBy { get; set; }
    
        public virtual CustomerSystem CustomerSystem { get; set; }
    }
}
