//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iDAS.Base
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class iDASCenterEntities : DbContext
    {
        public iDASCenterEntities()
        {
        }
    
        public virtual DbSet<CenterAction> CenterActions { get; set; }
        public virtual DbSet<CenterAuditAnswer> CenterAuditAnswers { get; set; }
        public virtual DbSet<CenterAuditCategoryQuestion> CenterAuditCategoryQuestions { get; set; }
        public virtual DbSet<CenterAuditQuestion> CenterAuditQuestions { get; set; }
        public virtual DbSet<CenterDepartmentRequirmentAttachment> CenterDepartmentRequirmentAttachments { get; set; }
        public virtual DbSet<CenterDepartmentRequirmentCategory> CenterDepartmentRequirmentCategories { get; set; }
        public virtual DbSet<CenterDepartmentRequirment> CenterDepartmentRequirments { get; set; }
        public virtual DbSet<CenterFunction> CenterFunctions { get; set; }
        public virtual DbSet<CenterKPICriteriaCategory> CenterKPICriteriaCategories { get; set; }
        public virtual DbSet<CenterKPICriteriaPoint> CenterKPICriteriaPoints { get; set; }
        public virtual DbSet<CenterKPICriteria> CenterKPICriterias { get; set; }
        public virtual DbSet<CenterModule> CenterModules { get; set; }
        public virtual DbSet<CenterRiskCategory> CenterRiskCategories { get; set; }
        public virtual DbSet<CenterRiskMethod> CenterRiskMethods { get; set; }
        public virtual DbSet<CenterRisk> CenterRisks { get; set; }
        public virtual DbSet<CenterRiskTreatment> CenterRiskTreatments { get; set; }
        public virtual DbSet<CenterSystem> CenterSystems { get; set; }
        public virtual DbSet<CustomerRegisterDataSize> CustomerRegisterDataSizes { get; set; }
        public virtual DbSet<CustomerRegisterProduct> CustomerRegisterProducts { get; set; }
        public virtual DbSet<CustomerRegisterService> CustomerRegisterServices { get; set; }
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<CustomerSystemMail> CustomerSystemMails { get; set; }
        public virtual DbSet<CustomerSystemModule> CustomerSystemModules { get; set; }
        public virtual DbSet<CustomerSystem> CustomerSystems { get; set; }
        public virtual DbSet<File> Files { get; set; }
        public virtual DbSet<ISOControl> ISOControls { get; set; }
        public virtual DbSet<ISOIndexCriteria> ISOIndexCriterias { get; set; }
        public virtual DbSet<ISOIndex> ISOIndexes { get; set; }
        public virtual DbSet<ISOIndexFunction> ISOIndexFunctions { get; set; }
        public virtual DbSet<ISOIndexModule> ISOIndexModules { get; set; }
        public virtual DbSet<ISOMeeting> ISOMeetings { get; set; }
        public virtual DbSet<ISONaceCode> ISONaceCodes { get; set; }
        public virtual DbSet<ISOStandardLibrary> ISOStandardLibraries { get; set; }
        public virtual DbSet<ISOStandardModule> ISOStandardModules { get; set; }
        public virtual DbSet<ISOStandard> ISOStandards { get; set; }
        public virtual DbSet<SystemDepartment> SystemDepartments { get; set; }
        public virtual DbSet<SystemInformation> SystemInformations { get; set; }
        public virtual DbSet<SystemOrganization> SystemOrganizations { get; set; }
        public virtual DbSet<SystemPermission> SystemPermissions { get; set; }
        public virtual DbSet<SystemRole> SystemRoles { get; set; }
        public virtual DbSet<SystemUser> SystemUsers { get; set; }
        public virtual DbSet<Tutorial> Tutorials { get; set; }
        public virtual DbSet<WebAuditor> WebAuditors { get; set; }
        public virtual DbSet<WebContact> WebContacts { get; set; }
        public virtual DbSet<WebCustomerCity> WebCustomerCities { get; set; }
        public virtual DbSet<WebCustomerComment> WebCustomerComments { get; set; }
        public virtual DbSet<WebCustomer> WebCustomers { get; set; }
        public virtual DbSet<WebFaqAnswer> WebFaqAnswers { get; set; }
        public virtual DbSet<WebFaqCategory> WebFaqCategories { get; set; }
        public virtual DbSet<WebFaqQuestion> WebFaqQuestions { get; set; }
        public virtual DbSet<WebLibrary> WebLibraries { get; set; }
        public virtual DbSet<WebLibraryCategory> WebLibraryCategories { get; set; }
        public virtual DbSet<WebLibraryItem> WebLibraryItems { get; set; }
        public virtual DbSet<WebNew> WebNews { get; set; }
        public virtual DbSet<WebNewsCategory> WebNewsCategories { get; set; }
        public virtual DbSet<WebProductCategory> WebProductCategories { get; set; }
        public virtual DbSet<WebProductDataSize> WebProductDataSizes { get; set; }
        public virtual DbSet<WebProductItem> WebProductItems { get; set; }
        public virtual DbSet<WebProductMethod> WebProductMethods { get; set; }
        public virtual DbSet<WebProductModule> WebProductModules { get; set; }
        public virtual DbSet<WebProduct> WebProducts { get; set; }
        public virtual DbSet<WebProductScope> WebProductScopes { get; set; }
        public virtual DbSet<WebRecruimentProfile> WebRecruimentProfiles { get; set; }
        public virtual DbSet<WebRecruiment> WebRecruiments { get; set; }
        public virtual DbSet<WebServiceCategory> WebServiceCategories { get; set; }
        public virtual DbSet<WebServiceComment> WebServiceComments { get; set; }
        public virtual DbSet<WebServiceItemFile> WebServiceItemFiles { get; set; }
        public virtual DbSet<WebServiceItem> WebServiceItems { get; set; }
        public virtual DbSet<WebService> WebServices { get; set; }
        public virtual DbSet<WebServiceStage> WebServiceStages { get; set; }
        public virtual DbSet<WebSitemap> WebSitemaps { get; set; }
    }
}
