//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iDAS.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class ISOStandard
    {
        public ISOStandard()
        {
            this.CenterDepartmentRequirments = new HashSet<CenterDepartmentRequirment>();
            this.CenterRiskCategories = new HashSet<CenterRiskCategory>();
            this.ISOControls = new HashSet<ISOControl>();
            this.ISOIndexes = new HashSet<ISOIndex>();
            this.ISOMeetings = new HashSet<ISOMeeting>();
            this.ISOStandardLibraries = new HashSet<ISOStandardLibrary>();
            this.ISOStandardModules = new HashSet<ISOStandardModule>();
        }
    
        public int ID { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public bool IsAnnex { get; set; }
        public bool IsActive { get; set; }
        public string UrlAvatar { get; set; }
        public Nullable<System.DateTime> CreateAt { get; set; }
        public Nullable<int> CreateBy { get; set; }
        public Nullable<System.DateTime> UpdateAt { get; set; }
        public Nullable<int> UpdateBy { get; set; }
    
        public virtual ICollection<CenterDepartmentRequirment> CenterDepartmentRequirments { get; set; }
        public virtual ICollection<CenterRiskCategory> CenterRiskCategories { get; set; }
        public virtual ICollection<ISOControl> ISOControls { get; set; }
        public virtual ICollection<ISOIndex> ISOIndexes { get; set; }
        public virtual ICollection<ISOMeeting> ISOMeetings { get; set; }
        public virtual ICollection<ISOStandardLibrary> ISOStandardLibraries { get; set; }
        public virtual ICollection<ISOStandardModule> ISOStandardModules { get; set; }
    }
}
