//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iDAS.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class WebFaqQuestion
    {
        public WebFaqQuestion()
        {
            this.WebFaqAnswers = new HashSet<WebFaqAnswer>();
        }
    
        public int ID { get; set; }
        public int WebFaqCategoryID { get; set; }
        public string Question { get; set; }
        public bool IsActive { get; set; }
        public bool IsDelete { get; set; }
        public int Position { get; set; }
        public Nullable<System.DateTime> CreateAt { get; set; }
        public Nullable<int> CreateBy { get; set; }
        public Nullable<System.DateTime> UpdateAt { get; set; }
        public Nullable<int> UpdateBy { get; set; }
    
        public virtual ICollection<WebFaqAnswer> WebFaqAnswers { get; set; }
        public virtual WebFaqCategory WebFaqCategory { get; set; }
    }
}
