//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iDAS.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class WebLibraryItem
    {
        public int ID { get; set; }
        public int WebLibraryID { get; set; }
        public string Name { get; set; }
        public Nullable<System.Guid> FileID { get; set; }
        public string VideoUrl { get; set; }
        public string Description { get; set; }
        public bool IsFirst { get; set; }
        public bool IsVideo { get; set; }
        public bool IsActive { get; set; }
        public bool IsDelete { get; set; }
        public int Position { get; set; }
        public Nullable<System.DateTime> CreateAt { get; set; }
        public Nullable<int> CreateBy { get; set; }
        public Nullable<System.DateTime> UpdateAt { get; set; }
        public Nullable<int> UpdateBy { get; set; }
    
        public virtual WebLibrary WebLibrary { get; set; }
    }
}
