//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iDAS.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class WebNew
    {
        public int ID { get; set; }
        public int WebNewsCategoryID { get; set; }
        public string Title { get; set; }
        public string Tags { get; set; }
        public string Html { get; set; }
        public Nullable<System.Guid> FileID { get; set; }
        public string Description { get; set; }
        public bool IsImportal { get; set; }
        public bool IsFirst { get; set; }
        public bool IsActive { get; set; }
        public bool IsDelete { get; set; }
        public string Author { get; set; }
        public Nullable<int> TotalView { get; set; }
        public Nullable<System.DateTime> RefreshAt { get; set; }
        public Nullable<System.DateTime> CreateAt { get; set; }
        public Nullable<int> CreateBy { get; set; }
        public Nullable<System.DateTime> UpdateAt { get; set; }
        public Nullable<int> UpdateBy { get; set; }
    
        public virtual File File { get; set; }
        public virtual WebNewsCategory WebNewsCategory { get; set; }
    }
}
