//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iDAS.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class WebProduct
    {
        public WebProduct()
        {
            this.CustomerRegisterProducts = new HashSet<CustomerRegisterProduct>();
            this.WebProductItems = new HashSet<WebProductItem>();
            this.WebProductModules = new HashSet<WebProductModule>();
        }
    
        public int ID { get; set; }
        public int WebProductCategoryID { get; set; }
        public Nullable<int> WebSitemapID { get; set; }
        public string Name { get; set; }
        public Nullable<System.Guid> FileID { get; set; }
        public string Tags { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> PublicAt { get; set; }
        public string Version { get; set; }
        public Nullable<int> TotalRegister { get; set; }
        public Nullable<int> Rate { get; set; }
        public bool IsActive { get; set; }
        public bool IsDelete { get; set; }
        public int Position { get; set; }
        public Nullable<System.DateTime> CreateAt { get; set; }
        public Nullable<int> CreateBy { get; set; }
        public Nullable<System.DateTime> UpdateAt { get; set; }
        public Nullable<int> UpdateBy { get; set; }
    
        public virtual ICollection<CustomerRegisterProduct> CustomerRegisterProducts { get; set; }
        public virtual WebProductCategory WebProductCategory { get; set; }
        public virtual ICollection<WebProductItem> WebProductItems { get; set; }
        public virtual ICollection<WebProductModule> WebProductModules { get; set; }
        public virtual WebSitemap WebSitemap { get; set; }
    }
}
