//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iDAS.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class WebProductMethod
    {
        public WebProductMethod()
        {
            this.CustomerRegisterProducts = new HashSet<CustomerRegisterProduct>();
            this.WebProductItems = new HashSet<WebProductItem>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public string Html { get; set; }
        public string Tags { get; set; }
        public string Description { get; set; }
        public bool IsActive { get; set; }
        public bool IsDelete { get; set; }
        public Nullable<System.DateTime> CreateAt { get; set; }
        public Nullable<int> CreateBy { get; set; }
        public Nullable<System.DateTime> UpdateAt { get; set; }
        public Nullable<int> UpdateBy { get; set; }
    
        public virtual ICollection<CustomerRegisterProduct> CustomerRegisterProducts { get; set; }
        public virtual ICollection<WebProductItem> WebProductItems { get; set; }
    }
}
