//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iDAS.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class WebProductCategory
    {
        public WebProductCategory()
        {
            this.WebProducts = new HashSet<WebProduct>();
        }
    
        public int ID { get; set; }
        public Nullable<int> CenterSystemID { get; set; }
        public Nullable<int> WebSitemapID { get; set; }
        public string Name { get; set; }
        public Nullable<System.Guid> FileID { get; set; }
        public string Tags { get; set; }
        public string Description { get; set; }
        public bool IsActive { get; set; }
        public bool IsDelete { get; set; }
        public int Position { get; set; }
        public Nullable<System.DateTime> CreateAt { get; set; }
        public Nullable<int> CreateBy { get; set; }
        public Nullable<System.DateTime> UpdateAt { get; set; }
        public Nullable<int> UpdateBy { get; set; }
    
        public virtual CenterSystem CenterSystem { get; set; }
        public virtual WebSitemap WebSitemap { get; set; }
        public virtual ICollection<WebProduct> WebProducts { get; set; }
    }
}
