//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iDAS.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class WebProductScope
    {
        public WebProductScope()
        {
            this.CustomerRegisterProducts = new HashSet<CustomerRegisterProduct>();
        }
    
        public int ID { get; set; }
        public string NaceCodes { get; set; }
        public string Description { get; set; }
        public bool IsProduction { get; set; }
        public bool IsService { get; set; }
        public float Factory { get; set; }
        public bool IsActive { get; set; }
        public bool IsDelete { get; set; }
        public Nullable<System.DateTime> CreateAt { get; set; }
        public Nullable<int> CreateBy { get; set; }
        public Nullable<System.DateTime> UpdateAt { get; set; }
        public Nullable<int> UpdateBy { get; set; }
    
        public virtual ICollection<CustomerRegisterProduct> CustomerRegisterProducts { get; set; }
    }
}
