//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iDAS.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class WebProductDataSize
    {
        public WebProductDataSize()
        {
            this.CustomerRegisterProducts = new HashSet<CustomerRegisterProduct>();
        }
    
        public int ID { get; set; }
        public Nullable<int> Size { get; set; }
        public string Unit { get; set; }
        public string Note { get; set; }
        public float UseTime { get; set; }
        public decimal Price { get; set; }
        public bool IsUpgrade { get; set; }
        public bool IsActive { get; set; }
        public bool IsDelete { get; set; }
        public Nullable<System.DateTime> CreateAt { get; set; }
        public Nullable<int> CreateBy { get; set; }
        public Nullable<System.DateTime> UpdateAt { get; set; }
        public Nullable<int> UpdateBy { get; set; }
    
        public virtual ICollection<CustomerRegisterProduct> CustomerRegisterProducts { get; set; }
    }
}
