//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iDAS.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class WebRecruiment
    {
        public WebRecruiment()
        {
            this.WebRecruimentProfiles = new HashSet<WebRecruimentProfile>();
        }
    
        public int ID { get; set; }
        public string Title { get; set; }
        public Nullable<System.Guid> FileID { get; set; }
        public string Html { get; set; }
        public string Role { get; set; }
        public string ContactName { get; set; }
        public string ContactPhone { get; set; }
        public string ContactMail { get; set; }
        public string Address { get; set; }
        public string Description { get; set; }
        public Nullable<int> TotalView { get; set; }
        public int Quatity { get; set; }
        public bool IsFirst { get; set; }
        public bool IsActive { get; set; }
        public bool IsDelete { get; set; }
        public Nullable<System.DateTime> FinishAt { get; set; }
        public Nullable<System.DateTime> RefreshAt { get; set; }
        public Nullable<System.DateTime> CreateAt { get; set; }
        public Nullable<int> CreateBy { get; set; }
        public Nullable<System.DateTime> UpdateAt { get; set; }
        public Nullable<int> UpdateBy { get; set; }
    
        public virtual ICollection<WebRecruimentProfile> WebRecruimentProfiles { get; set; }
    }
}
