//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iDAS.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class WebSitemap
    {
        public WebSitemap()
        {
            this.WebProductCategories = new HashSet<WebProductCategory>();
            this.WebProducts = new HashSet<WebProduct>();
            this.WebServiceCategories = new HashSet<WebServiceCategory>();
            this.WebServices = new HashSet<WebService>();
        }
    
        public int ID { get; set; }
        public Nullable<int> ParentID { get; set; }
        public string Text { get; set; }
        public string Tooltip { get; set; }
        public Nullable<System.Guid> FileID { get; set; }
        public string Url { get; set; }
        public string Html { get; set; }
        public string Layout { get; set; }
        public string Script { get; set; }
        public string Tags { get; set; }
        public bool IsPageDynamic { get; set; }
        public bool IsMenuTop { get; set; }
        public bool IsMenuRight { get; set; }
        public bool IsActive { get; set; }
        public bool IsDelete { get; set; }
        public int Position { get; set; }
        public Nullable<System.DateTime> CreateAt { get; set; }
        public Nullable<int> CreateBy { get; set; }
        public Nullable<System.DateTime> UpdateAt { get; set; }
        public Nullable<int> UpdateBy { get; set; }
    
        public virtual File File { get; set; }
        public virtual ICollection<WebProductCategory> WebProductCategories { get; set; }
        public virtual ICollection<WebProduct> WebProducts { get; set; }
        public virtual ICollection<WebServiceCategory> WebServiceCategories { get; set; }
        public virtual ICollection<WebService> WebServices { get; set; }
    }
}
