//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iDAS.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class WebService
    {
        public WebService()
        {
            this.WebServiceItems = new HashSet<WebServiceItem>();
            this.WebServiceStages = new HashSet<WebServiceStage>();
        }
    
        public int ID { get; set; }
        public int WebServiceCategoryID { get; set; }
        public Nullable<int> WebSitemapID { get; set; }
        public string Name { get; set; }
        public Nullable<System.Guid> FileID { get; set; }
        public string Tags { get; set; }
        public string Description { get; set; }
        public bool IsActive { get; set; }
        public bool IsDelete { get; set; }
        public int Position { get; set; }
        public Nullable<System.DateTime> CreateAt { get; set; }
        public Nullable<int> CreateBy { get; set; }
        public Nullable<System.DateTime> UpdateAt { get; set; }
        public Nullable<int> UpdateBy { get; set; }
    
        public virtual WebServiceCategory WebServiceCategory { get; set; }
        public virtual ICollection<WebServiceItem> WebServiceItems { get; set; }
        public virtual WebSitemap WebSitemap { get; set; }
        public virtual ICollection<WebServiceStage> WebServiceStages { get; set; }
    }
}
