//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iDAS.Base
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class iDASDataEntities: DbContext 
    {
        public virtual DbSet<SystemAction> SystemActions { get; set; }
        public virtual DbSet<SystemCustomer> SystemCustomers { get; set; }
        public virtual DbSet<SystemFunction> SystemFunctions { get; set; }
        public virtual DbSet<SystemGroup> SystemGroups { get; set; }
        public virtual DbSet<SystemModule> SystemModules { get; set; }
        public virtual DbSet<SystemOrganization> SystemOrganizations { get; set; }
        public virtual DbSet<SystemPermission> SystemPermissions { get; set; }
        public virtual DbSet<SystemRole> SystemRoles { get; set; }
        public virtual DbSet<SystemUserInfomation> SystemUserInfomations { get; set; }
        public virtual DbSet<SystemUser> SystemUsers { get; set; }
    }
}
